Repository projectdiscovery/nuclei, pull requests merged in 2020-11, with the labels that each got.

#393 Reworked progress bar with simpler stats display
  v2/go.mod
  v2/internal/progress/doc.go
  v2/internal/progress/progress.go
  v2/internal/progress/progress_noop.go
  v2/internal/progress/stdcapture.go
  v2/internal/runner/processor.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/workflows/var.go
Labels: Priority: High, Type: Bug

#397 adding fastdialer
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_http.go
Labels: Status: Review Needed, Type: Enhancement

#405 Hmap + clistats
  v2/go.mod
  v2/go.sum
  v2/internal/progress/progress.go
  v2/internal/runner/options.go
  v2/internal/runner/processor.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/globalratelimiter/ratelimit.go
Labels: Status: Review Needed, Type: Bug

#409 add reqURL to json output
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/output_http.go
Labels: Priority: Low, Status: Revision Needed

#412 Bugfix dns json output
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/executer/output_dns.go
Labels: Status: Review Needed, Type: Bug

#413 Nuclei 2.2.0
  v2/go.mod
  v2/go.sum
  v2/internal/progress/doc.go
  v2/internal/progress/progress.go
  v2/internal/progress/progress_noop.go
  v2/internal/progress/stdcapture.go
  v2/internal/runner/options.go
  v2/internal/runner/processor.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/output_dns.go
  v2/pkg/executer/output_http.go
  v2/pkg/globalratelimiter/ratelimit.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/dump.go
  v2/pkg/requests/util.go
  v2/pkg/workflows/compile.go
  v2/pkg/workflows/generator.go
  v2/pkg/workflows/var.go
  v2/pkg/workflows/workflows.go
Labels: Type: Enhancement

#420 improving parser regex
  v2/pkg/requests/bulk-http-request.go
Labels: Status: Review Needed, Type: Bug

#421 improved raw requests same header handling
  v2/pkg/requests/bulk-http-request.go
Labels: Status: Review Needed, Type: Bug

#425 updating fast dialer (support for hosts file)
  v2/go.mod
  v2/go.sum
Labels: Type: Bug, Type: Enhancement

#423 Payloads usable in DSL matchers
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/output_http.go
  v2/pkg/generators/dsl.go
  v2/pkg/generators/util.go
  v2/pkg/matchers/match.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/util.go
  v2/pkg/workflows/var.go
Labels: Status: Completed, enhancement
