Repository projectdiscovery/nuclei, pull requests merged in 2020-10, with the labels that each got.

#334 adding response time to DSL
  v2/pkg/executer/executer_http.go
  v2/pkg/matchers/match.go
  v2/pkg/matchers/util.go
Labels: Status: Accepted, Type: Enhancement

#338 Allow comments with # in nuclei-ignore
  v2/internal/runner/config.go
Labels: Status: In Progress

#329 Full Raw Http support
  v2/go.mod
  v2/go.sum
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/output_http.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/dump.go
  v2/pkg/requests/util.go
Labels: Priority: Low, Type: Enhancement

#343 connection header logic fix
  v2/pkg/requests/bulk-http-request.go
Labels: Status: Accepted, Type: Bug

#344 adding stop at first http match cli option
  v2/internal/runner/options.go
  v2/internal/runner/processor.go
  v2/pkg/executer/executer_http.go
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#341 Fixing Dockerfile v2
  Dockerfile
  README.md
Labels: Type: Bug

#335 Turbo intruder/pipelining
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/processor.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_http.go
  v2/pkg/globalratelimiter/ratelimit.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/workflows/var.go
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#348 reducing locking
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/http_utils.go
  v2/pkg/executer/output_http.go
  v2/pkg/generators/dsl.go
  v2/pkg/generators/util.go
  v2/pkg/globalratelimiter/ratelimit.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/generator.go
  v2/pkg/requests/util.go
Labels: Status: Review Needed, Type: Bug, Type: Enhancement

#356 fixed small logic bug in positional finite state machine
  v2/internal/runner/options.go
  v2/internal/runner/processor.go
  v2/pkg/executer/executer_http.go
  v2/pkg/requests/generator.go
Labels: Priority: High, Status: Review Needed, bug

#357 [Feature] Shared resolver cache
  v2/go.mod
  v2/go.sum
  v2/pkg/executer/executer_http.go
Labels: Priority: Medium, Status: Review Needed, enhancement

#364 [Feature] Adding mmh3 hashing
  v2/go.mod
  v2/go.sum
  v2/pkg/generators/dsl.go
  v2/pkg/generators/util.go
Labels: Status: Review Needed, Type: Enhancement

#366 fixed missing redirect handling with raw requests
  v2/go.mod
  v2/go.sum
  v2/pkg/executer/executer_http.go
  v2/pkg/requests/bulk-http-request.go
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#372 Added dynamic field in info key support
  v2/go.mod
  v2/go.sum
  v2/internal/runner/templates.go
  v2/pkg/executer/dns_utils.go
  v2/pkg/executer/http_utils.go
  v2/pkg/executer/output_dns.go
  v2/pkg/executer/output_http.go
  v2/pkg/executer/utils.go
  v2/pkg/templates/templates.go
  v2/pkg/workflows/workflows.go
Labels: Status: Accepted

#376 adding matcher per single request
  v2/go.mod
  v2/go.sum
  v2/pkg/executer/executer_http.go
  v2/pkg/matchers/match.go
  v2/pkg/matchers/util.go
Labels: Status: Accepted, Type: Enhancement

#371 Synced Race Condition Attack
  v2/pkg/executer/executer_http.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/syncedreadcloser/syncedreadcloser.go
Labels: Priority: Medium, Status: Completed, Status: Review Needed, Type: Enhancement

#379 adding burp collaborator support
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/collaborator/collaborator.go
  v2/pkg/generators/dsl.go
Labels: Status: Review Needed, Type: Enhancement

#362 [Feature] Nuclei State/Project File + Cache
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/processor.go
  v2/internal/runner/runner.go
  v2/pkg/atomicboolean/bool.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/projectfile/httputil.go
  v2/pkg/projectfile/project.go
Labels: Status: Review Needed, Type: Optimization

#381 fixing global dealer
  v2/internal/runner/processor.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_http.go
Labels: Type: Bug

#382 bugfix
  v2/pkg/executer/executer_http.go
Labels: Type: Bug

#388 [Bugfix] Request Dump
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_http.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/dump.go
Labels: Type: Bug
