Repository projectdiscovery/nuclei, pull requests merged in 2020-08, with the labels that each got.

#199 Fix #191 - Add support for severity filtering
  v2/internal/progress/progress.go
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
Labels: Status: Accepted

#198 Fix 180 - Add support for template exclusions
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
Labels: Status: Accepted

#208 fix no result found problem with and condition
  v2/pkg/executer/executer_dns.go
Labels: Status: Review Needed, Type: Bug

#219 Centralize template loaded info message, add output coloring
  v2/internal/runner/runner.go
Labels: Status: Accepted

#213 add json-requests for DNS
  README.md
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/output_dns.go
Labels: Status: Accepted, Status: Completed

#255 Colorizer initialization when using a custom workflow
  v2/pkg/workflows/var.go
Labels: Status: Completed

#267 Added switch to list available templates
  README.md
  internal/runner/config.go
  internal/runner/options.go
  internal/runner/paths.go
  internal/runner/processor.go
  internal/runner/runner.go
  internal/runner/templates.go
  internal/runner/update.go
  internal/runner/validate.go
  pkg/requests/bulk-http-request.go
Labels: Status: Review Needed

#266 Add template name to JSON output
  pkg/executer/http_utils.go
  pkg/executer/output_dns.go
  pkg/executer/output_http.go
Labels: Status: Review Needed
