Repository projectdiscovery/nuclei, pull requests merged in 2020-07, with the labels that each got.

#125 Defaults to an OR condition when no matchers-condition is specified in the rule
  v2/pkg/templates/compile.go
Labels: bug

#132 DSL Fix
  .github/workflows/build.yaml
  v2/pkg/executor/executer_http.go
Labels: bug

#152 using ld releaser
  .github/workflows/release.yml
Labels: bug

#142 improved workflow logic
  go.mod
  go.sum
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/executor/executer_http.go
  v2/pkg/executor/executor_dns.go
  v2/pkg/extractors/extractors.go
  v2/pkg/generators/util.go
  v2/pkg/matchers/matchers.go
  v2/pkg/requests/http-request.go
  v2/pkg/templates/compile.go
  v2/pkg/workflows/var.go
Labels: Priority: Medium, Status: Review Needed, enhancement

#140 Add description to Template files
  v2/pkg/executor/http_utils.go
  v2/pkg/executor/output_dns.go
  v2/pkg/executor/output_http.go
  v2/pkg/templates/templates.go
  v2/pkg/workflows/workflows.go
Labels: Priority: Medium, Status: Available, Type: Enhancement

#158 kval extractor
  go.mod
  go.sum
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/executer/dns_utils.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/http_utils.go
  v2/pkg/executer/output_dns.go
  v2/pkg/executer/output_http.go
  v2/pkg/extractors/compile.go
  v2/pkg/extractors/extract.go
  v2/pkg/extractors/extractors.go
  v2/pkg/workflows/var.go
Labels: Priority: Low, enhancement

#160 Advanced Workflows
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_http.go
  v2/pkg/requests/http-request.go
  v2/pkg/workflows/var.go
  v2/pkg/workflows/workflows.go
Labels: Status: In Progress, Status: Review Needed, Type: Discussion, Type: Enhancement

#155 Fix 147 support multiple input templates
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/internal/runner/validate.go
Labels: Status: In Progress, Status: Review Needed, Type: Enhancement

#168 Workflow additional features
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/output_http.go
  v2/pkg/generators/util.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/util.go
  v2/pkg/templates/compile.go
  v2/pkg/templates/templates.go
  v2/pkg/workflows/var.go
Labels: Status: Completed

#157 Option for request/response output in JSON matches
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/http_utils.go
  v2/pkg/executer/output_http.go
Labels: Status: Completed

#171 Support Template Wildcarding
  v2/internal/runner/runner.go
Labels: Status: Review Needed

#174 engine parallelism fix
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/atomicboolean/bool.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/extractors/compile.go
  v2/pkg/extractors/extractors.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/generator.go
  v2/pkg/templates/compile.go
  v2/pkg/workflows/var.go
Labels: Priority: Critical, Status: Review Needed, bug

#179 Bugfix latest pending issues
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/internal/runner/update.go
  v2/pkg/workflows/compile.go
  v2/pkg/workflows/var.go
  v2/pkg/workflows/workflows.go
Labels: Status: Review Needed, bug

#181 adding speed to workflows
  v2/internal/runner/runner.go
Labels: Status: Review Needed, bug

#149 Enumeration progressbar
  .gitignore
  v2/go.mod
  v2/go.sum
  v2/internal/progress/doc.go
  v2/internal/progress/progress.go
  v2/internal/progress/stdcapture.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/dns-request.go
  v2/pkg/templates/templates.go
  v2/pkg/workflows/var.go
Labels: Priority: Medium, Status: Accepted

#182 making progress bar respect silent flag
  v2/internal/runner/banner.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/workflows/var.go
Labels: Status: Accepted, Status: Completed

#189 runtime error + -no-pbar cli option
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/executer/executer_http.go
  v2/pkg/requests/generator.go
Labels: Status: Accepted, Status: Completed

#194 no-pbar to pbar
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
Labels: Status: Review Needed, bug

#192 fixing relative path issue
  v2/go.mod
  v2/go.sum
  v2/pkg/templates/compile.go
  v2/pkg/templates/templates.go
Labels: Status: Review Needed, bug

#193 updating gologger module
  v2/go.mod
  v2/go.sum
Labels: Status: Review Needed, bug
