Repository projectdiscovery/nuclei, pull requests merged in 2020-09, with the labels that each got.

#288 Use pbar + silent
  README.md
  internal/runner/runner.go
Labels: Status: Review Needed

#281 Setting custom headers values with colon
  pkg/executer/executer_http.go
Labels: Status: Completed

#294 Same-name-headers are chunked into 1 line when matching
  pkg/executer/http_utils.go
Labels: Status: Review Needed

#316 Fix for return workflow results
  internal/runner/processor.go
  internal/runner/runner.go
Labels: Status: Review Needed

#315 Added severity to match output message
  internal/progress/progress.go
  internal/runner/processor.go
  internal/runner/runner.go
  internal/runner/templates.go
  pkg/colorizer/colorizer.go
  pkg/executer/executer_dns.go
  pkg/executer/executer_http.go
  pkg/executer/output_dns.go
  pkg/executer/output_http.go
  pkg/workflows/var.go
Labels: Status: Review Needed

#287 Handle port and path from input
  internal/runner/processor.go
  pkg/executer/executer_http.go
  pkg/requests/bulk-http-request.go
Labels: Status: Completed

#322 fixing goreleaser target
  .github/workflows/build.yaml
  Dockerfile
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/bufwriter/bufwriter.go
  v2/internal/progress/doc.go
  v2/internal/progress/progress.go
  v2/internal/progress/progress_noop.go
  v2/internal/progress/stdcapture.go
  v2/internal/runner/banner.go
  v2/internal/runner/config.go
  v2/internal/runner/doc.go
  v2/internal/runner/options.go
  v2/internal/runner/paths.go
  v2/internal/runner/processor.go
  v2/internal/runner/runner.go
  v2/internal/runner/templates.go
  v2/internal/runner/update.go
  v2/pkg/atomicboolean/bool.go
  v2/pkg/colorizer/colorizer.go
  v2/pkg/executer/dns_utils.go
  v2/pkg/executer/executer_dns.go
  v2/pkg/executer/executer_http.go
  v2/pkg/executer/http_utils.go
  v2/pkg/executer/output_dns.go
  v2/pkg/executer/output_http.go
  v2/pkg/extractors/compile.go
  v2/pkg/extractors/doc.go
  v2/pkg/extractors/extract.go
  v2/pkg/extractors/extractors.go
  v2/pkg/generators/attack.go
  v2/pkg/generators/clusterbomb.go
  v2/pkg/generators/dsl.go
  v2/pkg/generators/pitchfork.go
  v2/pkg/generators/sniper.go
  v2/pkg/generators/util.go
  v2/pkg/matchers/compile.go
  v2/pkg/matchers/doc.go
  v2/pkg/matchers/match.go
  v2/pkg/matchers/match_test.go
  v2/pkg/matchers/matchers.go
  v2/pkg/matchers/util.go
  v2/pkg/requests/bulk-http-request.go
  v2/pkg/requests/dns-request.go
  v2/pkg/requests/doc.go
  v2/pkg/requests/generator.go
  v2/pkg/requests/util.go
  v2/pkg/templates/compile.go
  v2/pkg/templates/doc.go
  v2/pkg/templates/templates.go
  v2/pkg/workflows/compile.go
  v2/pkg/workflows/doc.go
  v2/pkg/workflows/var.go
  v2/pkg/workflows/workflows.go
Labels: Status: Review Needed, Type: Bug

#323 fixing dockerfile
  Dockerfile
Labels: Type: Bug

#321 base64_decode fix
  v2/pkg/generators/dsl.go
Labels: Type: Bug

#251 Don't quit http requests on an error
  v2/pkg/executer/executer_http.go
Labels: Status: Review Needed, Type: Bug
