Repository projectdiscovery/nuclei, pull requests merged in 2020-05, with the labels that each got.

#72 verbose proxy url validation
  go.mod
  go.sum
  internal/runner/validate.go
Labels: enhancement

#83 Add Docker support
  Dockerfile
  README.md
Labels: enhancement

#76 [WIP] Fuzzing + DSL support in requests
  go.mod
  go.sum
  internal/runner/banner.go
  pkg/executor/executer_http.go
  pkg/executor/output_http.go
  pkg/generators/attack.go
  pkg/generators/clusterbomb.go
  pkg/generators/dsl.go
  pkg/generators/pitchfork.go
  pkg/generators/sniper.go
  pkg/generators/util.go
  pkg/matchers/compile.go
  pkg/requests/http-request.go
  pkg/requests/util.go
  pkg/templates/compile.go
Labels: enhancement, help wanted

#86 custom header via cli
  internal/runner/options.go
  internal/runner/runner.go
  pkg/executor/executer_http.go
  pkg/requests/http-request.go
Labels: enhancement

#87 added new option description
  README.md
Labels: documentation

#88 -
  README.md
Labels: documentation

#89 modules update
  go.mod
  go.sum
Labels: enhancement

#90 Corrected package extension in readme
  README.md
Labels: documentation
