Repository projectdiscovery/nuclei, pull requests merged in 2021-10, with the labels that each got.

#1059 Adding headless support on alpine + Use of installed browser
  Dockerfile
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/headless/engine/engine.go
  v2/pkg/types/types.go
Labels: Type: Bug

#1079 Adding support for custom resolvers in DNS templates
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dnsclientpool/clientpool.go
Labels: Type: Enhancement

#1204 Add error log option
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/output/file_output_writer.go
  v2/pkg/output/output.go
  v2/pkg/output/output_test.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/offlinehttp/request.go
  v2/pkg/types/types.go
  v2/pkg/utils/utils.go
  v2/pkg/utils/utils_test.go
Labels: hacktoberfest-accepted
