Repository projectdiscovery/nuclei, pull requests merged in 2021-12, with the labels that each got.

#1288 Reusing dynamically extracted values as iterators in http request
  v2/Makefile
  v2/pkg/operators/operators.go
  v2/pkg/operators/operators_test.go
  v2/pkg/protocols/common/generators/maps.go
  v2/pkg/protocols/common/generators/maps_test.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/request_test.go
Labels: Status: Review Needed

#1315 validate flag updates
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/catalog/loader/loader.go
Labels: Status: Review Needed, Type: Enhancement

#1284 Added default fields for DNS requests
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dns_test.go
  v2/pkg/protocols/dns/operators_test.go
  v2/pkg/protocols/dns/request_test.go
  v2/pkg/templates/templates_doc_examples.go
Labels: Status: Review Needed

#1313 Improving headless test cases
  integration_tests/headless/headless-basic.yaml
  integration_tests/headless/headless-extract-values.yaml
  integration_tests/headless/headless-header-action.yaml
  v2/cmd/integration-test/headless.go
  v2/cmd/integration-test/integration-test.go
Labels: Status: Review Needed, Type: Maintenance

#1320 Fixing payloads path during validation
  .github/workflows/template-validate.yml
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/parsers/parser.go
  v2/pkg/protocols/common/generators/validate.go
Labels: Status: Completed, Type: Bug

#1135 Disabling no-sandbox in headless engine
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/protocols/headless/engine/engine.go
Labels: Status: Review Needed

#1340 Improving path handling on windows
  v2/go.mod
  v2/go.sum
  v2/pkg/catalog/path.go
  v2/pkg/protocols/common/generators/validate.go
Labels: Status: Review Needed, Type: Bug

#1341 Fixing templates bundle unzip on windows
  v2/go.sum
  v2/internal/runner/update.go
  v2/pkg/protocols/common/generators/validate.go
Labels: Status: Completed, Type: Bug

#1296 feat: Improve DSL function UX
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
  v2/pkg/operators/matchers/compile.go
  v2/pkg/operators/matchers/match.go
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/reporting/exporters/es/elasticsearch.go
  v2/pkg/reporting/exporters/markdown/markdown.go
  v2/pkg/reporting/exporters/sarif/sarif.go
Labels: Type: Enhancement

#1357 Adding race condition test
  .github/workflows/build-test.yml
Labels: Status: Review Needed, Type: Enhancement

#1355 Removing linux/arm - Missing chrome package
  .github/workflows/dockerhub-push.yml
Labels: Type: Bug

#1356 Trim paths info from released binary
  v2/.goreleaser.yml
Labels: Status: Review Needed, Type: Enhancement

#1347 Support major os
  .github/workflows/build-test.yml
  .github/workflows/functional-test.yml
  v2/cmd/functional-test/run.sh
Labels: Type: Enhancement

#1212 Misc changes to update logic
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/internal/runner/update.go
Labels: Status: Completed

#1260 Extending deny list to support filenames and folders
  v2/pkg/protocols/file/file.go
  v2/pkg/protocols/file/file_test.go
  v2/pkg/protocols/file/find.go
  v2/pkg/protocols/file/find_test.go
  v2/pkg/protocols/file/operators_test.go
  v2/pkg/protocols/file/request_test.go
Labels: Status: Completed, Type: Enhancement

#1389 Fixing wrong function/variable name in whois integration test
  v2/cmd/integration-test/whois.go
Labels: Status: Review Needed, Type: Bug

#1390 Updating GH action to use macos-latest
  .github/workflows/build-test.yml
  .github/workflows/functional-test.yml
Labels: Status: Review Needed, Type: Maintenance

#1247 Adding support for aws request signing
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/expressions/variables.go
  v2/pkg/protocols/common/protocolinit/init.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/signature.go
  v2/pkg/protocols/http/signer/aws.go
  v2/pkg/protocols/http/signer/signer.go
  v2/pkg/protocols/http/signerpool/signerpool.go
  v2/pkg/templates/compile.go
  v2/pkg/templates/templates.go
Labels: Status: Review Needed, Type: Enhancement

#1407 Fixing CVE annotate crash
  v2/cmd/cve-annotate/main.go
Labels: Status: Completed, Type: Bug

#1408 Removing invalid negative paths for windows
  integration_tests/http/self-contained.yaml
  integration_tests/network/self-contained.yaml
  v2/internal/runner/update_test.go
  v2/internal/runner/update_unix_test.go
Labels: Status: Review Needed, Type: Bug

#1416 Improving projectfile http request matching
  v2/pkg/projectfile/project.go
Labels: Status: Review Needed, Type: Bug

#1417 Add stop at first match for interactsh matchers
  integration_tests/http/interactsh-stop-at-first-match.yaml
  v2/cmd/integration-test/http.go
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/network/request.go
Labels: Status: Review Needed

#1432 Adding support for navigation history to matchers
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/engine/rules.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/headless/request.go
Labels: Status: Review Needed, Type: Enhancement

#1434 Adding support for automatic http fallback retry for interactsh
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/http/build_request_test.go
Labels: Status: Completed, Type: Enhancement
