Repository projectdiscovery/nuclei, pull requests merged in 2021-09, with the labels that each got.

#753 Do not create a new issue in Jira if it is already opened
  v2/cmd/nuclei/issue-tracker-config.yaml
  v2/pkg/reporting/trackers/jira/jira.go
Labels: Status: Completed, Type: Enhancement

#1026 GitHub rate limit bug fix
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/internal/runner/templates.go
  v2/internal/runner/update.go
  v2/pkg/catalog/config/config.go
  v2/pkg/protocols/http/request.go
Labels: Status: Completed

#1058 Fixing extended dns edge cases
  v2/pkg/protocols/dns/dns.go
Labels: Type: Bug

#1060 Removing unwanted bytes operation for unsafe requests
  v2/pkg/protocols/http/raw/raw.go
Labels: Type: Bug

#1040 disk cleanups
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/reporting/exporters/es/elasticsearch.go
  v2/pkg/reporting/exporters/markdown/markdown.go
  v2/pkg/reporting/exporters/sarif/sarif.go
  v2/pkg/reporting/reporting.go
  v2/pkg/types/types.go
Labels: Status: Completed, Status: Review Needed

#1036 resolves project-discovery/nuclei#822 - Add severity label to GitHub reporter
  v2/pkg/reporting/trackers/github/github.go
  v2/pkg/reporting/trackers/gitlab/gitlab.go
  v2/pkg/reporting/trackers/jira/jira.go
Labels: Status: Completed

#1046 Add payload, global variable, helper support to matchers
  v2/pkg/operators/matchers/match.go
  v2/pkg/operators/matchers/match_test.go
  v2/pkg/protocols/dns/operators.go
  v2/pkg/protocols/file/operators.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/network/network.go
  v2/pkg/protocols/network/operators.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/offlinehttp/operators.go
Labels: Status: In Progress

#1061 docker workflow improvements
  .github/workflows/dockerhub-push.yml
Labels: Type: Bug
