Repository projectdiscovery/nuclei, pull requests merged in 2021-04, with the labels that each got.

#670 Fix can't set user agent in templates
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/http.go
Labels: Type: Bug

#683 adding shared fastdialer + missing cleanup
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/protocolinit/init.go
  v2/pkg/protocols/common/protocolstate/state.go
  v2/pkg/protocols/headless/engine/engine.go
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/headless/engine/page_actions_test.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/network/networkclientpool/clientpool.go
Labels: Status: Review Needed, Type: Bug

#688 Fix missing IP in the JSON when URLs contain hostname:port
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed
