Repository projectdiscovery/nuclei, pull requests merged in 2021-02, with the labels that each got.

#562 Add headless chrome based templates support
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/internal/runner/templates.go
  v2/internal/testutils/testutils.go
  v2/pkg/operators/operators.go
  v2/pkg/protocols/headless/engine/action.go
  v2/pkg/protocols/headless/engine/engine.go
  v2/pkg/protocols/headless/engine/engine_unix.go
  v2/pkg/protocols/headless/engine/engine_windows.go
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/headless/engine/instance.go
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/engine/rules.go
  v2/pkg/protocols/headless/headless.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/headless/request_test.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/network/network.go
  v2/pkg/protocols/protocols.go
  v2/pkg/templates/compile.go
  v2/pkg/templates/preprocessors.go
  v2/pkg/templates/templates.go
  v2/pkg/types/types.go
  v2/pkg/workflows/workflows.go
Labels: Status: In Progress, Type: Enhancement

#558 rawhttp - misc fixes
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/utils.go
Labels: Status: In Progress, Type: Bug, Type: Enhancement

#543 Adding dep bot
  .github/dependabot.yml
  v2/go.mod
  v2/go.sum
Labels: Type: Maintenance

#565 removing unused options
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/request.go
Labels: Type: Bug

#563 refactoring dockerfile
  Dockerfile
Labels: Type: Bug

#544 Adding tls support
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/network/network.go
  v2/pkg/protocols/network/network_test.go
  v2/pkg/protocols/network/request.go
Labels: Status: In Progress, Type: Enhancement

#570 Adding dns fallback support
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/network/networkclientpool/clientpool.go
Labels: Type: Bug

#569 add missing rawhttp option override
  v2/pkg/protocols/http/utils.go
Labels: Status: Completed, Type: Bug

#572 Bumping fastdialer version
  v2/go.mod
  v2/go.sum
Labels: Type: Maintenance

#574 Fixing output endpoint in unsafe request without host header
  v2/pkg/protocols/http/raw/raw.go
Labels: Type: Bug

#575 removing dump request for race conditions
  v2/pkg/protocols/http/request.go
Labels: Status: In Progress, Type: Bug
