Repository projectdiscovery/nuclei, pull requests merged in 2021-07, with the labels that each got.

#823 Nuclei Parallel HTTP Map crash fix
  v2/pkg/protocols/http/request.go
Labels: Status: Completed

#848 [Bugfix] Missing headers in request dump
  v2/pkg/protocols/http/request.go
Labels: Type: Bug

#851 Allow for User supplied Preprocessor Logic
  v2/pkg/catalog/loader/loader.go
  v2/pkg/templates/compile.go
  v2/pkg/templates/preprocessors.go
  v2/pkg/templates/workflows.go
Labels: Status: Review Needed

#862 Refreshed CLI Help menu with Grouping options
  README.md
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
Labels: Status: Completed
