Repository projectdiscovery/nuclei, pull requests merged in 2021-11, with the labels that each got.

#1130 Add case-insensitive option to template
  integration_tests/http/get-case-insensitive.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/operators/extractors/compile.go
  v2/pkg/operators/extractors/extract.go
  v2/pkg/operators/extractors/extractors.go
  v2/pkg/operators/matchers/compile.go
  v2/pkg/operators/matchers/match.go
  v2/pkg/operators/matchers/matchers.go
  v2/pkg/protocols/dns/operators.go
  v2/pkg/protocols/dns/operators_test.go
  v2/pkg/protocols/file/operators.go
  v2/pkg/protocols/file/operators_test.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/http/operators_test.go
  v2/pkg/protocols/network/operators.go
  v2/pkg/protocols/network/operators_test.go
Labels: Status: Completed, hacktoberfest-accepted

#1203 feat: In case of binary data, show a hexadecimal view as well #1080
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/common/helpers/responsehighlighter/hexdump.go
  v2/pkg/protocols/common/helpers/responsehighlighter/response_highlighter.go
  v2/pkg/protocols/common/helpers/responsehighlighter/response_highlighter_test.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/network/request.go
Labels: Status: Completed, hacktoberfest-accepted

#1182 Fixed raw request path not correct with unsafe
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/raw/raw_test.go
Labels: Status: Review Needed

#1123 Remote template workflow lists
  integration_tests/loader/basic.yaml
  integration_tests/loader/condition-matched.yaml
  integration_tests/loader/get-headers.yaml
  integration_tests/loader/get.yaml
  integration_tests/loader/template-list.yaml
  integration_tests/loader/workflow-list.yaml
  v2/cmd/integration-test/integration-test.go
  v2/cmd/integration-test/loader.go
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/internal/testutils/integration.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/catalog/loader/remote_loader.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#1185 Added more variables for DNS requests
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dns_test.go
Labels: Status: Completed

#1186 Added new type and exclude-type flag
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/catalog/loader/filter/tag_filter.go
  v2/pkg/catalog/loader/filter/tag_filter_test.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/parsers/parser.go
  v2/pkg/templates/templates.go
  v2/pkg/templates/types/types.go
  v2/pkg/types/types.go
Labels: Status: In Progress

#1219 Unique Interactsh URL
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/internal/testutils/testutils.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/request_generator.go
  v2/pkg/protocols/network/request.go
  v2/pkg/types/types.go
Labels: Status: Completed

#1208 Enhance hexdump content highlighting
  v2/pkg/protocols/common/helpers/responsehighlighter/hexdump.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/network/request.go
Labels: Status: Completed

#1230 Adding support for custom headers via CLI in raw http requests
  integration_tests/http/raw-unsafe-request.yaml
  v2/go.mod
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/raw/raw_test.go
Labels: Status: Completed

#1232 fix #1173: perform matching on all redirect responses instead of final
  integration_tests/http/get-redirects-chain-headers.yaml
  v2/cmd/integration-test/http.go
  v2/cmd/integration-test/integration-test.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/utils.go
Labels: Status: Completed, Status: Review Needed

#1225 feat: Checking socks5 proxy before launching a scan #1001
  README.md
  README_CN.md
  v2/cmd/nuclei/main.go
  v2/internal/runner/options.go
  v2/internal/runner/proxy.go
  v2/internal/testutils/testutils.go
  v2/pkg/protocols/headless/engine/engine.go
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/types/proxy.go
  v2/pkg/types/types.go
Labels: Status: Completed

#1241 Fixing http test using local http mock server
  v2/pkg/protocols/offlinehttp/read_response_test.go
Labels: Type: Bug

#1239 Better error handling for return value of helper http library
  v2/pkg/protocols/http/request.go
Labels: Status: Completed, Type: Bug

#1237 [Bug] Improving error handling in client certificate helper library
  v2/pkg/protocols/headless/engine/engine.go
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/utils/utils.go
Labels: Status: Completed, Status: Review Needed

#1177 Added high level nuclei architecture overview
  DESIGN.md
Labels: Status: Completed

#1245 struct to enum changes for Dns Type
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dns_test.go
  v2/pkg/protocols/dns/dns_types.go
  v2/pkg/protocols/dns/operators_test.go
  v2/pkg/protocols/dns/request_test.go
  v2/pkg/templates/templates_doc_examples.go
Labels: Status: Review Needed, Type: Enhancement

#1233 enum changes for network type
  v2/pkg/protocols/network/network.go
  v2/pkg/protocols/network/network_input_types.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/network/request_test.go
Labels: Status: Review Needed, Type: Enhancement

#1234 enum changes for http method
  SYNTAX-REFERENCE.md
  nuclei-jsonschema.json
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/cluster_test.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/http_method_types.go
  v2/pkg/protocols/http/operators_test.go
  v2/pkg/templates/templates_doc.go
  v2/pkg/templates/templates_doc_examples.go
Labels: Status: Review Needed, Type: Enhancement

#1236 Adding dns trace support in dns templates
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/protocols/common/expressions/variables.go
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/operators.go
  v2/pkg/protocols/dns/operators_test.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/network/network.go
Labels: Status: Completed, Status: Review Needed, Type: Enhancement

#1217 Extractor + Headless Actions structures to enums
  v2/pkg/operators/extractors/compile.go
  v2/pkg/operators/extractors/extractor_types.go
  v2/pkg/operators/extractors/extractors.go
  v2/pkg/protocols/dns/operators_test.go
  v2/pkg/protocols/dns/request_test.go
  v2/pkg/protocols/file/operators_test.go
  v2/pkg/protocols/file/request_test.go
  v2/pkg/protocols/headless/engine/action.go
  v2/pkg/protocols/headless/engine/action_types.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/engine/page_actions_test.go
  v2/pkg/protocols/http/operators_test.go
  v2/pkg/protocols/network/operators_test.go
  v2/pkg/protocols/network/request_test.go
  v2/pkg/protocols/offlinehttp/operators_test.go
  v2/pkg/templates/templates_doc_examples.go
Labels: Status: Review Needed, Type: Enhancement

#1246 struct to enums changes for Matchers
  v2/pkg/operators/matchers/compile.go
  v2/pkg/operators/matchers/match_test.go
  v2/pkg/operators/matchers/matchers.go
  v2/pkg/operators/matchers/matchers_types.go
  v2/pkg/operators/operators.go
  v2/pkg/protocols/dns/operators_test.go
  v2/pkg/protocols/dns/request_test.go
  v2/pkg/protocols/file/operators_test.go
  v2/pkg/protocols/file/request_test.go
  v2/pkg/protocols/http/operators_test.go
  v2/pkg/protocols/network/operators_test.go
  v2/pkg/protocols/network/request_test.go
  v2/pkg/protocols/offlinehttp/operators_test.go
  v2/pkg/templates/templates_doc_examples.go
Labels: Status: Review Needed, Type: Enhancement

#1256 Tag based struct validation
  integration_tests/test-issue-tracker-config1.yaml
  integration_tests/test-issue-tracker-config2.yaml
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/reporting/exporters/es/elasticsearch.go
  v2/pkg/reporting/trackers/github/github.go
  v2/pkg/reporting/trackers/gitlab/gitlab.go
  v2/pkg/reporting/trackers/jira/jira.go
  v2/pkg/types/types.go
  v2/pkg/utils/yaml/yaml_decode_wrapper.go
Labels: Status: Completed

#1255 Adding support for clustering within workflow
  DESIGN.md
  v2/internal/runner/runner.go
  v2/pkg/core/execute.go
  v2/pkg/protocols/common/clusterer/clusterer.go
  v2/pkg/templates/cluster.go
  v2/pkg/templates/workflows.go
Labels: Status: Completed, Type: Enhancement

#1272 Added matched-status flag + template-path and url to output
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/output/format_screen.go
  v2/pkg/output/output.go
  v2/pkg/output/output_test.go
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/protocols/common/helpers/writer/writer.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/dns/operators.go
  v2/pkg/protocols/dns/operators_test.go
  v2/pkg/protocols/file/operators.go
  v2/pkg/protocols/file/operators_test.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/http/operators_test.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/network/operators.go
  v2/pkg/protocols/network/operators_test.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/offlinehttp/operators.go
  v2/pkg/protocols/offlinehttp/operators_test.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/templates/cluster.go
  v2/pkg/testutils/testutils.go
  v2/pkg/types/types.go
  v2/pkg/utils/template_path.go
Labels: Status: Completed

#1285 Fixed a crash with http module
  v2/pkg/protocols/http/request.go
Labels: Status: Completed

#1286 Fixed stdin input parsing bug causing nuclei to hang
  v2/internal/runner/options.go
Labels: Status: Review Needed

#1279 Unsafe flag with base template
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Bug

#1306 fix: #1274 spawned nuclei child process hangs reading stdin
  v2/internal/runner/options.go
Labels: Status: Review Needed

#1282 Added additional variables for network + simplified logic
  v2/pkg/protocols/network/network.go
  v2/pkg/protocols/network/network_test.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/network/request_test.go
Labels: Status: Review Needed
