Repository projectdiscovery/nuclei, pull requests merged in 2021-06, with the labels that each got.

#751 Integration with Jira Standalone server
  v2/cmd/nuclei/issue-tracker-config.yaml
  v2/pkg/reporting/trackers/jira/jira.go
Labels: Status: Review Needed, Type: Enhancement

#781 Adding hex output for network request/response
  v2/pkg/protocols/network/request.go
Labels: enhancement

#767 Fixed typo "Moroover" in readme
  README.md
Labels: documentation

#788 [Bug] Fixing matchers when internal extractors are active
  v2/pkg/protocols/http/operators.go
Labels: Type: Bug

#787 [Feature] Adding rawhttp timeout
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
Labels: Type: Enhancement

#782 Fixing chrome zombie processes termination
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/headless/engine/engine.go
  v2/pkg/protocols/headless/engine/engine_unix.go
  v2/pkg/protocols/headless/engine/engine_windows.go
Labels: Type: Bug

#779 Adding support for misconfigured gzip header from server
  v2/pkg/protocols/http/request.go
Labels: bug
