Repository projectdiscovery/nuclei, pull requests merged in 2021-08, with the labels that each got.

#896 Added support for rate limit per minute
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#898 Adding JSON extractor support
  v2/go.mod
  v2/go.sum
  v2/pkg/operators/extractors/compile.go
  v2/pkg/operators/extractors/extract.go
  v2/pkg/operators/extractors/extractors.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/http/operators_test.go
  v2/pkg/types/interfaces.go
Labels: Status: Review Needed

#913 Fixing automatic keep alive handling with manual connection header
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
Labels: Type: Bug

#918 Bumping interactsh version to 0.0.4
  .golangci.yml
  v2/go.mod
  v2/go.sum
Labels: Type: Maintenance

#916 Adding support for global env variables
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/common/generators/env.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#915 Adding support for user defined variables via CLI
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/generators/maps.go
  v2/pkg/protocols/common/generators/slice.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#925 Adding support to ignore random internal errors
  v2/pkg/protocols/http/request.go
Labels: Type: Bug

#924 fixed pitchfork validation
  v2/pkg/protocols/common/generators/generators.go
Labels: Status: Review Needed

#949 Fixing slice runtime error due to unset byte slice capacity
  v2/pkg/reporting/dedupe/dedupe.go
Labels: Type: Bug

#950 Fixing wrong type conversion in DSL helper
  v2/pkg/operators/common/dsl/dsl.go
Labels: Type: Bug

#953 Fixing some DSL helpers logic
  v2/pkg/operators/common/dsl/dsl.go
Labels: Type: Bug

#958 Fixing priority in response to DSL mapping
  v2/pkg/protocols/http/operators.go
Labels: Type: Bug
