Repository projectdiscovery/nuclei, pull requests merged in 2022-06, with the labels that each got.

#2092 Increasing timeout and fixed error msg
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/engine/page_actions_test.go
Labels: Status: Review Needed, Type: Bug

#1966 Add optional line number for file templates by default
  README.md
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/file/request.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2101 ssl protocol with ms flag crash
  v2/pkg/output/output.go
  v2/pkg/protocols/ssl/ssl.go
Labels: Status: Review Needed, Type: Bug

#2096 change dsl evaluate warning messages to error
  v2/pkg/operators/matchers/match.go
Labels: Status: Review Needed, Type: Bug

#2091 Adding Client TLS1.0
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/websocket/websocket.go
Labels: Status: Review Needed, Type: Maintenance

#2138 protect against multiple unnecessary Init calls
  v2/pkg/protocols/common/protocolstate/state.go
Labels: Type: Enhancement

#2148 Improving literals detection in expression engine
  v2/pkg/protocols/common/expressions/expressions.go
  v2/pkg/protocols/common/expressions/variables.go
  v2/pkg/protocols/common/expressions/variables_test.go
Labels: Type: Bug

#2173 Adding nil operator check on clustering
  v2/pkg/templates/cluster.go
Labels: Status: Review Needed, Type: Bug

#2193 Adding http request validation at compile time
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/validate.go
Labels: Status: Review Needed, Type: Bug

#2178 Add self diagnostic functionality
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/healthcheck.go
  v2/internal/runner/runner.go
  v2/pkg/types/types.go
Labels: Type: Maintenance

#2196 Added aes_gcm implementation for DSL function
  integration_tests/http/dsl-functions.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
Labels: Status: Review Needed

#2218 Added exclude-matchers support for template & matchers
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/operators/operators.go
  v2/pkg/protocols/common/utils/excludematchers/excludematchers.go
  v2/pkg/protocols/common/utils/excludematchers/excludematchers_test.go
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/operators_test.go
  v2/pkg/protocols/dns/request_test.go
  v2/pkg/protocols/file/file.go
  v2/pkg/protocols/file/operators_test.go
  v2/pkg/protocols/file/request_test.go
  v2/pkg/protocols/headless/headless.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/network/network.go
  v2/pkg/protocols/protocols.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/protocols/whois/whois.go
  v2/pkg/templates/cluster.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2233 Added http request timeout support with annotations
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/http/request_annotations.go
Labels: Status: Review Needed

#2223 Added enhancements for http variables support
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed

#2171 Adding prototype for unexpected fields validation in matchers
  v2/pkg/operators/matchers/compile.go
  v2/pkg/operators/matchers/validate.go
  v2/pkg/operators/matchers/validate_test.go
Labels: Status: Review Needed, Type: Maintenance

#2191 Replacing hasstdin with helper library
  README.md
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/pkg/core/inputs/hybrid/hmap.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Maintenance
