Repository projectdiscovery/nuclei, pull requests merged in 2022-10, with the labels that each got.

#2671 Unit test for GetRandomIPWithCidr and fixes
  v2/pkg/protocols/common/randomip/randomip.go
  v2/pkg/protocols/common/randomip/randomip_test.go
Labels: Type: Bug, Type: Maintenance

#2654 Improved dsl test by removing coloring + fix datatime tests
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
Labels: Status: Review Needed

#2675 cidr input support #2665
  v2/pkg/core/inputs/hybrid/hmap.go
  v2/pkg/core/inputs/hybrid/hmap_test.go
Labels: Status: Review Needed, Type: Enhancement

#2688 Added response truncation support with flags
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/http/request.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2697 Adding custom cancel function
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/request_annotations.go
  v2/pkg/protocols/http/request_annotations_test.go
Labels: Type: Bug

#2704 Fixing docker build missing gcc binary
  Dockerfile
Labels: Type: Bug

#2716 Issue 212/ratelimit library
  v2/cmd/integration-test/code.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/protocols/protocols.go
  v2/pkg/testutils/testutils.go
  v2/pkg/utils/ratelimit/ratelimit.go
  v2/pkg/utils/ratelimit/ratelimit_test.go
Labels: Type: Maintenance

#2712 Add AS input support
  v2/go.mod
  v2/go.sum
  v2/pkg/core/inputs/hybrid/hmap.go
  v2/pkg/core/inputs/hybrid/hmap_test.go
  v2/pkg/core/inputs/hybrid/tests/AS134029.txt
  v2/pkg/core/inputs/hybrid/tests/AS14421.txt
Labels: Status: Review Needed

#2717 updates to execute func in integration-test.go
  v2/cmd/integration-test/integration-test.go
Labels: Type: Maintenance

#2721 reordering unsafe test in the map
  v2/cmd/integration-test/http.go
Labels: Type: Bug, Type: Maintenance

#2707 Adding automatic request condition detection
  integration_tests/http/request-condition.yaml
  v2/pkg/protocols/http/cluster.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/request_condition.go
  v2/pkg/protocols/http/validate.go
Labels: Type: Enhancement

#2724 Added attack-type option to override template attack-type
  README.md
  integration_tests/http/custom-attack-type.yaml
  v2/cmd/integration-test/http.go
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/common/generators/generators.go
  v2/pkg/protocols/common/generators/generators_test.go
  v2/pkg/protocols/headless/headless.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/request_generator_test.go
  v2/pkg/protocols/network/network.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2614 Added probing for URL + input based on protocol
  v2/cmd/nuclei/main.go
  v2/internal/runner/enumerate.go
  v2/internal/runner/inputs.go
  v2/internal/runner/runner.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/core/engine.go
  v2/pkg/core/execute.go
  v2/pkg/core/inputs/hybrid/hmap.go
  v2/pkg/core/inputs/inputs.go
  v2/pkg/input/input.go
  v2/pkg/input/input_test.go
  v2/pkg/protocols/common/automaticscan/automaticscan.go
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/protocols/offlinehttp/request.go
  v2/pkg/protocols/protocols.go
  v2/pkg/templates/types/types.go
  v2/pkg/templates/workflows.go
  v2/pkg/types/types.go
  v2/pkg/workflows/workflows.go
Labels: Status: Review Needed

#2407 set content_length as len(body) if response ContentLength is -1
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/offlinehttp/operators.go
  v2/pkg/protocols/utils/utils.go
  v2/pkg/protocols/utils/utils_test.go
Labels: Type: Bug

#2722 Improving unsafe uri path
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/raw/raw_test.go
  v2/pkg/protocols/http/request.go
Labels: Type: Bug

#2763 add dns protocol ratelimit
  v2/pkg/protocols/dns/request.go
Labels: Type: Maintenance
