Repository projectdiscovery/nuclei, pull requests merged in 2022-09, with the labels that each got.

#2522 Added tlsx integration to nuclei
  .github/workflows/build-test.yml
  integration_tests/ssl/basic-ztls.yaml
  integration_tests/ssl/basic.yaml
  integration_tests/ssl/custom-cipher.yaml
  integration_tests/ssl/custom-version.yaml
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/ssl/ciphers.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/ssl/version.go
  v2/pkg/protocols/utils/utils.go
Labels: Status: Review Needed

#2568 Optional use of local chrome for headless tests via tags
  v2/pkg/protocols/headless/engine/page_actions_test.go
  v2/pkg/testutils/testheadless/headless_local.go
  v2/pkg/testutils/testheadless/headless_runtime.go
Labels: Type: Maintenance

#2611 Added multi-protocol requests support for templates
  v2/go.mod
  v2/go.sum
  v2/pkg/templates/compile.go
Labels: Status: Review Needed

#2594 Added workflow names based condition
  v2/pkg/core/workflow_execute.go
  v2/pkg/core/workflow_execute_test.go
  v2/pkg/templates/workflows.go
  v2/pkg/workflows/workflows.go
  v2/pkg/workflows/workflows_test.go
Labels: Status: Review Needed

#2536 implementation of rate limiter with bucket refill and unrestricted token burst
  v2/cmd/integration-test/code.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/protocols.go
  v2/pkg/testutils/testutils.go
  v2/pkg/utils/ratelimit/ratelimit.go
  v2/pkg/utils/ratelimit/ratelimit_test.go
Labels: Status: Revision Needed, Type: Bug

#2605 Added default config generation for reporting options
  v2/cmd/integration-test/custom-dir.go
  v2/internal/runner/runner.go
  v2/pkg/reporting/exporters/es/elasticsearch.go
  v2/pkg/reporting/reporting.go
  v2/pkg/reporting/trackers/github/github.go
  v2/pkg/reporting/trackers/gitlab/gitlab.go
  v2/pkg/reporting/trackers/jira/jira.go
Labels: Status: Review Needed

#2372 Add `sort(list)`, `sort(string)`, `uniq(list)`, `uniq(string)` helper functions
  integration_tests/http/dsl-functions.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
Labels: Status: Review Needed

#2655 Adding same host redirect support
  integration_tests/http/get-host-redirects.yaml
  v2/cmd/integration-test/http.go
  v2/cmd/nuclei/main.go
  v2/internal/runner/options.go
  v2/pkg/operators/extractors/extract_test.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/http/validate.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#2642 Forcing conns to be gc-ed by default disabling keep-alive
  v2/pkg/protocols/http/http.go
Labels: Status: Review Needed, Type: Bug
