Repository projectdiscovery/nuclei, pull requests merged in 2022-02, with the labels that each got.

#1562 Disable internal standard library logger
  v2/internal/runner/options.go
Labels: Status: Review Needed, Type: Bug

#1560 Differentiate between interact matchers and markers
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Bug

#1559 Fixing exit at first match with extractors
  integration_tests/http/stop-at-first-match-with-extractors.yaml
  integration_tests/http/stop-at-first-match.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Bug

#1564 Adding support for DNS CAA query
  integration_tests/dns/caa.yaml
  v2/cmd/integration-test/dns.go
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dns_types.go
Labels: Status: Review Needed, Type: Enhancement

#1555 Adding support for CLI/ENV vars to headless
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/headless/engine/instance.go
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/engine/util.go
  v2/pkg/protocols/headless/request.go
Labels: Status: Review Needed, Type: Enhancement

#1561 Implementing incremental expression replacement
  v2/pkg/protocols/common/expressions/expressions.go
  v2/pkg/protocols/common/replacer/replacer.go
Labels: Status: Review Needed, Type: Bug

#1529 Add support for ztls for ssl/crypto templates
  integration_tests/ssl/basic-ztls.yaml
  integration_tests/ssl/basic.yaml
  v2/cmd/integration-test/http.go
  v2/cmd/integration-test/integration-test.go
  v2/cmd/integration-test/network.go
  v2/cmd/integration-test/ssl.go
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/protocolstate/state.go
  v2/pkg/protocols/ssl/ciphers.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/ssl/version.go
  v2/pkg/testutils/integration.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Enhancement

#1574 Adding support for payloads in headless protocol
  integration_tests/headless/headless-payloads.yaml
  v2/cmd/integration-test/headless.go
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/engine/page_actions_test.go
  v2/pkg/protocols/headless/headless.go
  v2/pkg/protocols/headless/request.go
Labels: Status: Completed, Type: Enhancement

#1577 update: increased limit for file protocol
  v2/pkg/protocols/file/file.go
Labels: Type: Enhancement

#1583 Typo fixes
  DESIGN.md
  v2/pkg/catalog/loader/remote_loader.go
  v2/pkg/catalog/path.go
  v2/pkg/core/engine.go
  v2/pkg/core/execute.go
  v2/pkg/protocols/file/file.go
  v2/pkg/protocols/headless/headless.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/signature.go
  v2/pkg/protocols/http/signer/aws.go
  v2/pkg/protocols/network/network.go
  v2/pkg/protocols/offlinehttp/offlinehttp.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/reporting/trackers/gitlab/gitlab.go
  v2/pkg/templates/cluster.go
  v2/pkg/templates/templates_doc.go
  v2/pkg/types/resume.go
Labels: Status: Review Needed, Type: Maintenance

#1569 Uniform behavior for input CLI flags
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/model/types/severity/severities.go
  v2/pkg/templates/types/types.go
  v2/pkg/types/types.go
  v2/pkg/utils/utils.go
Labels: Status: Completed, Type: Enhancement

#1495 Added line number for file results + stats fixes
  v2/pkg/operators/matchers/match.go
  v2/pkg/operators/matchers/matchers.go
  v2/pkg/operators/operators.go
  v2/pkg/output/format_screen.go
  v2/pkg/output/output.go
  v2/pkg/protocols/common/helpers/eventcreator/eventcreator.go
  v2/pkg/protocols/file/file.go
  v2/pkg/protocols/file/operators.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/file/request_test.go
Labels: Status: Revision Needed

#1605 Added pagination support using page and size
  v2/cmd/nuclei-client/client.go
  v2/cmd/nuclei-client/issues.go
  v2/cmd/nuclei-client/scans.go
  v2/cmd/nuclei-client/settings.go
  v2/cmd/nuclei-client/targets.go
  v2/cmd/nuclei-client/templates.go
  v2/cmd/nuclei-server/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/rest/api/api.go
  v2/pkg/rest/api/client/client.go
  v2/pkg/rest/api/client/client_test.go
  v2/pkg/rest/api/client/issues.go
  v2/pkg/rest/api/client/issues_test.go
  v2/pkg/rest/api/client/mocks/issues_mock_handler.go
  v2/pkg/rest/api/client/mocks/scan_mock_handler.go
  v2/pkg/rest/api/client/mocks/targets_mock_handler.go
  v2/pkg/rest/api/client/scans.go
  v2/pkg/rest/api/client/scans_test.go
  v2/pkg/rest/api/client/settings.go
  v2/pkg/rest/api/client/settings_test.go
  v2/pkg/rest/api/client/targets.go
  v2/pkg/rest/api/client/targets_test.go
  v2/pkg/rest/api/client/template.go
  v2/pkg/rest/api/client/template_test.go
  v2/pkg/rest/api/handlers/helpers.go
  v2/pkg/rest/api/handlers/issues.go
  v2/pkg/rest/api/handlers/issues_test.go
  v2/pkg/rest/api/handlers/scans.go
  v2/pkg/rest/api/handlers/targets.go
  v2/pkg/rest/api/handlers/templates.go
  v2/pkg/rest/api/services/scans/scans.go
  v2/pkg/rest/api/services/scans/worker_output.go
  v2/pkg/rest/api/services/updater/updater.go
  v2/pkg/rest/db/dbsql/models.go
  v2/pkg/rest/db/dbsql/querier.go
  v2/pkg/rest/db/dbsql/schema.sql.go
  v2/pkg/rest/db/migrate.go
  v2/pkg/rest/db/mock_db.go
  v2/pkg/rest/db/schema.sql
Labels: Status: Review Needed

#1639 Allow random resume file generation on conflict + made resume string
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/types/resume.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#1646 Added interaction event highlighting support in debug mode
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/network/request.go
Labels: Status: Review Needed

#1645 Added gzip_decode helper function
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
Labels: Status: Review Needed

#1659 Added unknown as severity value when it is not known
  README.md
  v2/pkg/model/types/severity/severity.go
  v2/pkg/model/types/severity/severity_test.go
Labels: Status: Review Needed
