Repository projectdiscovery/nuclei, pull requests merged in 2022-08, with the labels that each got.

#2359 Additional helpers
  integration_tests/http/dsl-functions.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
Labels: Status: Review Needed, Type: Enhancement

#2292 Added profile-mem flag for Memory profiling
  DESIGN.md
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
Labels: Status: Review Needed, Type: Enhancement

#2414 Added support for blank Request-URI which specifies no slash suffix
  v2/pkg/protocols/http/raw/raw.go
Labels: Status: Review Needed, Type: Bug

#2318 Added initial catalog interface implementation
  v2/cmd/cve-annotate/main.go
  v2/cmd/integration-test/code.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/internal/runner/templates.go
  v2/pkg/catalog/catalogue.go
  v2/pkg/catalog/disk/catalog.go
  v2/pkg/catalog/disk/find.go
  v2/pkg/catalog/disk/path.go
  v2/pkg/catalog/loader/filter/path_filter.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/catalog/loader/loader_test.go
  v2/pkg/parsers/parser.go
  v2/pkg/parsers/parser_test.go
  v2/pkg/parsers/workflow_loader.go
  v2/pkg/protocols/common/generators/generators.go
  v2/pkg/protocols/common/generators/generators_test.go
  v2/pkg/protocols/common/generators/load.go
  v2/pkg/protocols/http/request_generator_test.go
  v2/pkg/protocols/protocols.go
  v2/pkg/templates/compile.go
  v2/pkg/testutils/testutils.go
  v2/pkg/utils/utils.go
Labels: Status: Review Needed

#2423 added validation for headless templates
  v2/pkg/catalog/loader/loader.go
Labels: Type: Bug

#2464 Added reference based tag addition to templates
  v2/cmd/cve-annotate/main.go
Labels: Status: Review Needed

#2476 Fixed request annotation based timeout bugs + tests + misc
  integration_tests/http/annotation-timeout.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/request_annotations.go
  v2/pkg/protocols/http/request_annotations_test.go
Labels: Status: Review Needed

#2350 Memory usage optimizations
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
  v2/pkg/operators/extractors/compile.go
  v2/pkg/operators/matchers/compile.go
  v2/pkg/operators/matchers/match.go
  v2/pkg/operators/matchers/match_test.go
  v2/pkg/protocols/common/expressions/expressions.go
  v2/pkg/protocols/common/expressions/variables.go
  v2/pkg/protocols/common/replacer/replacer.go
  v2/pkg/protocols/common/replacer/replacer_test.go
Labels: Status: Review Needed

#2486 Fixed loader templateConfig nil pointer crash
  v2/internal/runner/runner.go
Labels: Status: Review Needed

#2488 Fixed fatal panic in http header map read
  v2/pkg/protocols/http/utils.go
Labels: Status: Review Needed

#2456 Added show-actions flag to display headless actions
  README.md
  v2/cmd/nuclei/main.go
  v2/internal/runner/options.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2442 Added variable debug support with debug mode
  v2/pkg/protocols/common/helpers/eventcreator/eventcreator.go
  v2/pkg/protocols/common/utils/vardump/dump.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/protocols/whois/whois.go
Labels: Status: Review Needed

#2399 added custom config flag
  v2/cmd/integration-test/custom-dir.go
  v2/cmd/integration-test/integration-test.go
  v2/cmd/nuclei/main.go
  v2/internal/runner/healthcheck.go
  v2/pkg/catalog/config/config.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#2374 Adding advanced template filtering
  v2/cmd/cve-annotate/main.go
  v2/cmd/docgen/docgen.go
  v2/cmd/functional-test/main.go
  v2/cmd/functional-test/testcases.txt
  v2/cmd/integration-test/loader.go
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/internal/runner/update.go
  v2/internal/runner/update_test.go
  v2/pkg/catalog/loader/filter/tag_filter.go
  v2/pkg/catalog/loader/filter/tag_filter_test.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/parsers/parser.go
  v2/pkg/parsers/parser_test.go
  v2/pkg/parsers/workflow_loader.go
  v2/pkg/projectfile/httputil.go
  v2/pkg/protocols/common/automaticscan/automaticscan.go
  v2/pkg/protocols/file/find_test.go
  v2/pkg/protocols/file/request_test.go
  v2/pkg/protocols/headless/engine/engine.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/utils.go
  v2/pkg/protocols/offlinehttp/find_test.go
  v2/pkg/reporting/dedupe/dedupe.go
  v2/pkg/reporting/dedupe/dedupe_test.go
  v2/pkg/reporting/exporters/es/elasticsearch.go
  v2/pkg/reporting/exporters/markdown/markdown.go
  v2/pkg/types/types.go
  v2/pkg/utils/monitor/monitor.go
Labels: Status: Revision Needed, Type: Enhancement

#2384 add option to specify network interface
  README.md
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/common/protocolstate/state.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Enhancement

#2500 Updated goflags to latest + misc
  DESIGN.md
  v2/cmd/integration-test/code.go
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/pkg/model/types/severity/severities.go
  v2/pkg/protocols/common/generators/env.go
  v2/pkg/protocols/common/generators/slice.go
  v2/pkg/protocols/dns/dnsclientpool/clientpool.go
  v2/pkg/templates/types/types.go
  v2/pkg/types/types.go
Labels: Status: Review Needed
