Repository projectdiscovery/nuclei, pull requests merged in 2022-11, with the labels that each got.

#2788 Fixed invalid fields in jsonschema request structures
  SYNTAX-REFERENCE.md
  nuclei-jsonschema.json
  v2/pkg/operators/operators.go
Labels: Status: Review Needed

#2679 Added fuzzing support for query params + var dump feature
  integration_tests/http/fuzz-query.yaml
  v2/cmd/integration-test/http.go
  v2/cmd/nuclei/main.go
  v2/cmd/tools/fuzzplayground/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/pkg/protocols/common/expressions/expressions.go
  v2/pkg/protocols/common/expressions/variables.go
  v2/pkg/protocols/common/expressions/variables_test.go
  v2/pkg/protocols/common/helpers/eventcreator/eventcreator.go
  v2/pkg/protocols/common/utils/vardump/dump.go
  v2/pkg/protocols/common/variables/variables.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/fuzz/doc.go
  v2/pkg/protocols/http/fuzz/execute.go
  v2/pkg/protocols/http/fuzz/execute_test.go
  v2/pkg/protocols/http/fuzz/fuzz.go
  v2/pkg/protocols/http/fuzz/fuzz_test.go
  v2/pkg/protocols/http/fuzz/parts.go
  v2/pkg/protocols/http/fuzz/parts_test.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/request_generator.go
  v2/pkg/protocols/http/request_generator_test.go
  v2/pkg/protocols/http/utils/variables.go
  v2/pkg/protocols/http/utils/variables_test.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/protocols/whois/whois.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2790 Fixed nested expression replacement using fasttemplate
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/replacer/replacer.go
  v2/pkg/protocols/common/replacer/replacer_test.go
Labels: Status: Review Needed

#2630 Issue 2613 custom template GitHub
  .github/workflows/build-test.yml
  README.md
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/github.go
  v2/internal/runner/github_test.go
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/internal/runner/update.go
  v2/pkg/testutils/testutils.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2819 Replacing rdap with fixed fork
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/protocolinit/init.go
  v2/pkg/protocols/whois/rdapclientpool/clientpool.go
  v2/pkg/protocols/whois/whois.go
Labels: Type: Bug

#2709 Adding support to scan all v4/v6 IPs
  integration_tests/http/get-all-ips.yaml
  integration_tests/http/get-without-scheme.yaml
  v2/cmd/integration-test/code.go
  v2/cmd/integration-test/http.go
  v2/cmd/nuclei/main.go
  v2/cmd/tools/fuzzplayground/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/enumerate.go
  v2/internal/runner/inputs.go
  v2/internal/runner/nucleicloud/types.go
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/core/engine.go
  v2/pkg/core/execute.go
  v2/pkg/core/inputs/hybrid/hmap.go
  v2/pkg/core/inputs/hybrid/hmap_test.go
  v2/pkg/core/inputs/hybrid/options.go
  v2/pkg/core/inputs/inputs.go
  v2/pkg/core/workflow_execute.go
  v2/pkg/core/workflow_execute_test.go
  v2/pkg/protocols/common/automaticscan/automaticscan.go
  v2/pkg/protocols/common/contextargs/contextargs.go
  v2/pkg/protocols/common/contextargs/metainput.go
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/dns/request_test.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/file/request_test.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/request_test.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/network/request_test.go
  v2/pkg/protocols/offlinehttp/request.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/ssl/ssl_test.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/protocols/whois/whois.go
  v2/pkg/templates/cluster.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#2838 Add `split` DSL function
  integration_tests/http/dsl-functions.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
Labels: Type: Enhancement

#2786 Issue 2254 uncover integration
  README.md
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/core/engine.go
  v2/pkg/core/inputs/hybrid/hmap.go
  v2/pkg/core/inputs/hybrid/hmap_test.go
  v2/pkg/core/inputs/inputs.go
  v2/pkg/protocols/common/uncover/uncover.go
  v2/pkg/testutils/testutils.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2900 Reverting retryablehttp-go to fix custom http client
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/generators/load_test.go
Labels: Type: Bug

#2884 Race condition tests
  .github/workflows/build-test.yml
  v2/cmd/functional-test/targets.txt
Labels: github_actions

#2897 Update goflag to solve the header truncated issue
  v2/go.mod
  v2/go.sum
Labels: Status: Review Needed

#2908 Mocking dns server
  v2/pkg/core/inputs/hybrid/hmap_test.go
Labels: Type: Bug

#2909 Making matcher name case insensitive
  v2/pkg/model/types/stringslice/stringslice.go
  v2/pkg/operators/operators.go
  v2/pkg/reporting/exporters/sarif/sarif.go
  v2/pkg/reporting/format/format.go
  v2/pkg/utils/utils.go
  v2/pkg/workflows/workflows.go
Labels: Type: Bug

#2923 Remove nuclei-updatecheck-api as dependency
  v2/go.mod
  v2/go.sum
  v2/internal/runner/update.go
  v2/pkg/protocols/common/updatecheck/client.go
Labels: Status: Review Needed

#2925 enhance sarif output (closes #2608)
  v2/go.mod
  v2/go.sum
  v2/pkg/reporting/exporters/sarif/sarif.go
Labels: Type: Enhancement
