Repository projectdiscovery/nuclei, pull requests merged in 2022-07, with the labels that each got.

#2215 Add new sites to ban list
  v2/cmd/cve-annotate/main.go
Labels: Priority: Low, Type: Enhancement

#2192 Improving RFC request/response passive parsing
  integration_tests/offlinehttp/data/req-resp-with-http-keywords.txt
  integration_tests/offlinehttp/rfc-req-resp.yaml
  v2/cmd/integration-test/integration-test.go
  v2/cmd/integration-test/offline-http.go
  v2/pkg/protocols/offlinehttp/read_response.go
Labels: Status: Review Needed, Type: Bug

#2276 Adding more offline http tests
  integration_tests/offlinehttp/offline-allowed-paths.yaml
  integration_tests/offlinehttp/offline-raw.yaml
  v2/cmd/integration-test/offline-http.go
Labels: Status: Review Needed, Type: Maintenance

#2262 use go-homedir instead of standard os.userhomedir
  v2/internal/runner/healthcheck.go
  v2/internal/runner/update.go
  v2/pkg/catalog/config/config.go
  v2/pkg/utils/template_path.go
Labels: Status: Review Needed, Type: Bug

#2275 Issue 2227 ntv flag run new templates added in specific version
  README.md
  README_CN.md
  v2/cmd/functional-test/testcases.txt
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Enhancement

#2161 Adding prototype of request flow override annotations
  .gitignore
  v2/pkg/protocols/http/request_annotations.go
  v2/pkg/protocols/http/request_generator.go
Labels: Status: Review Needed, Type: Enhancement

#2319 Added timeout context cancellation to http requests
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed

#2323 Added CISA KEV annotation support to cve-annotate
  v2/cmd/cve-annotate/main.go
Labels: Status: Review Needed

#2325 Added global variables support to SSL protocol
  v2/pkg/protocols/ssl/ssl.go
Labels: Status: Review Needed

#2310 missing ip in json
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Bug

#2340 Fixing race conditions
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/types/resume.go
Labels: Status: Review Needed, Type: Bug
