Repository projectdiscovery/nuclei, pull requests merged in 2022-03, with the labels that each got.

#1634 Refactoring file templates to handle large files in chunks + deprecated methods refactor
  v2/cmd/cve-annotate/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/internal/runner/update.go
  v2/pkg/operators/operators.go
  v2/pkg/operators/operators_test.go
  v2/pkg/output/format_screen.go
  v2/pkg/output/output.go
  v2/pkg/protocols/common/helpers/eventcreator/eventcreator.go
  v2/pkg/protocols/file/file.go
  v2/pkg/protocols/file/file_test.go
  v2/pkg/protocols/file/find_test.go
  v2/pkg/protocols/file/operators.go
  v2/pkg/protocols/file/operators_test.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/file/request_test.go
  v2/pkg/protocols/headless/engine/page_actions_test.go
  v2/pkg/protocols/http/race/syncedreadcloser.go
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/signer/aws.go
  v2/pkg/protocols/http/utils.go
  v2/pkg/protocols/offlinehttp/read_response_test.go
  v2/pkg/protocols/offlinehttp/request.go
  v2/pkg/protocols/utils/utils.go
  v2/pkg/reporting/exporters/es/elasticsearch.go
  v2/pkg/reporting/trackers/jira/jira.go
  v2/pkg/utils/utils.go
Labels: Status: Review Needed, Type: Enhancement

#1688 Adding truncation info on debug
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Enhancement

#1685 Added more tests and ciphersuits for SSL protocol
  integration_tests/ssl/custom-cipher.yaml
  integration_tests/ssl/custom-version.yaml
  v2/cmd/integration-test/http.go
  v2/cmd/integration-test/network.go
  v2/cmd/integration-test/ssl.go
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/ssl/ciphers.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/testutils/integration.go
Labels: Status: Review Needed

#1694 #1332 integration test for template loading
  integration_tests/dns/cname-fingerprint.yaml
  v2/cmd/integration-test/integration-test.go
  v2/cmd/integration-test/template-path.go
Labels: Status: Review Needed, Type: Enhancement

#1712 Migrated Ice3man543/nvd to organization repo
  v2/cmd/cve-annotate/main.go
  v2/go.mod
  v2/go.sum
Labels: Status: Review Needed

#1704 Adding number/string conversion helpers
  v2/go.mod
  v2/go.sum
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
  v2/pkg/operators/operators.go
Labels: Status: Review Needed, Type: Enhancement

#1517 Added initial automatic workflow implementation
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/internal/runner/templates.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/core/engine.go
  v2/pkg/core/execute.go
  v2/pkg/protocols/common/automaticscan/doc.go
  v2/pkg/protocols/common/automaticscan/workflow.go
  v2/pkg/templates/log.go
  v2/pkg/templates/log_test.go
  v2/pkg/types/types.go
Labels: Status: Completed

#1725 Implements github request with token fallback
  v2/internal/runner/update.go
Labels: Status: Review Needed, Type: Bug

#1738 Fix for nil unexpected return value in workflow execution
  v2/internal/runner/runner.go
Labels: Type: Bug

#1742 integration test for template update/install
  v2/cmd/integration-test/integration-test.go
  v2/cmd/integration-test/template-dir.go
Labels: Status: Review Needed, Type: Enhancement

#1744 Random IP Helper Function
  integration_tests/http/dsl-functions.yaml
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
  v2/pkg/protocols/common/randomip/randomip.go
Labels: Type: Enhancement

#1696 Adding proxy support for internal standard HTTP requests
  README.md
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/proxy.go
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/reporting/exporters/es/elasticsearch.go
  v2/pkg/reporting/reporting.go
  v2/pkg/reporting/trackers/github/github.go
  v2/pkg/reporting/trackers/gitlab/gitlab.go
  v2/pkg/reporting/trackers/jira/jira.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Enhancement

#1754 Fixing stats printing with invalid templates
  v2/pkg/progress/progress.go
Labels: Status: Review Needed, Type: Bug

#1755 Adding HexOrString helper
  v2/pkg/reporting/format/format.go
  v2/pkg/types/interfaces.go
Labels: Status: Review Needed, Type: Bug

#1746 Stats counter + Mime type filter
  integration_tests/headless/headless-extract-values.yaml
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/file/file.go
  v2/pkg/protocols/file/find.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/headless/engine/page_actions_test.go
Labels: Status: Review Needed, Type: Enhancement, Type: Bug

#1780 Evaluate payload helpers before matching
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed
