Repository projectdiscovery/nuclei, pull requests merged in 2022-04, with the labels that each got.

#1790 Adding support to skip unused payloads
  v2/pkg/protocols/http/http.go
Labels: Status: Review Needed, Type: Bug

#1727 Issue 1705 save responses on disk
  README.md
  v2/cmd/nuclei/main.go
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/output/output.go
  v2/pkg/output/output_test.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/testutils/testutils.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Enhancement

#1806 improving default template path logic
  v2/cmd/integration-test/template-path.go
  v2/internal/runner/update.go
  v2/pkg/reporting/exporters/sarif/sarif.go
  v2/pkg/utils/template_path.go
Labels: Status: Completed, Type: Bug

#1813 Fixing integration test condition of dsl-functions.yaml
  v2/cmd/integration-test/http.go
Labels: Type: Bug

#1758 Sanitizing special chars in markdown file paths
  v2/go.mod
  v2/go.sum
  v2/pkg/reporting/exporters/markdown/markdown.go
Labels: Status: Completed, Type: Bug

#1825 Fixes #1808
  v2/cmd/integration-test/template-path.go
  v2/internal/runner/update.go
  v2/pkg/testutils/integration.go
Labels: Status: Review Needed, Type: Bug

#1840 truncated http response check
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Bug

#1839 Improving body dump logic for HTTP requests
  v2/pkg/protocols/http/utils.go
Labels: Status: Review Needed, Type: Bug

#1821 clean up old resume files
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
Labels: Status: Review Needed, Type: Bug

#1811 adding support for digest authentication
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/http.go
Labels: Status: Review Needed, Type: Enhancement

#1853 Fixing nil crash on json stats print
  v2/pkg/progress/progress.go
Labels: Status: Review Needed, Type: Bug

#1805 HTTP Requests Annotation Prototype
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/request_annotations.go
Labels: Status: Review Needed, Type: Enhancement

#1864 nil value check
  v2/internal/runner/runner.go
  v2/pkg/catalog/find.go
  v2/pkg/protocols/common/automaticscan/automaticscan.go
Labels: Type: Bug

#1870 automatic-scan with custom dir
  v2/pkg/protocols/common/automaticscan/automaticscan.go
Labels: Status: Completed, Type: Bug

#1873 adding support for dsl extractors
  v2/pkg/operators/extractors/compile.go
  v2/pkg/operators/extractors/extract.go
  v2/pkg/operators/extractors/extractor_types.go
  v2/pkg/operators/extractors/extractors.go
  v2/pkg/operators/extractors/util.go
  v2/pkg/protocols/dns/operators.go
  v2/pkg/protocols/file/operators.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/network/operators.go
  v2/pkg/protocols/offlinehttp/operators.go
  v2/pkg/protocols/protocols.go
Labels: Status: Review Needed, Type: Enhancement

#1901 Disable redirects
  README.md
  integration_tests/http/disable-redirects.yaml
  v2/cmd/integration-test/http.go
  v2/cmd/nuclei/main.go
  v2/internal/runner/options.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Enhancement

#1902 Fixed nuclei go example + added relevant integration test
  DESIGN.md
  integration_tests/code/test.yaml
  v2/cmd/integration-test/code.go
  v2/cmd/integration-test/integration-test.go
Labels: Type: Maintenance

#1908 Disable static compilation for osx
  v2/Makefile
Labels: Status: Review Needed, Type: Maintenance

#1903 Automatic fallback to system chrome on alpine via musl detection
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/headless/engine/engine.go
Labels: Status: Review Needed, Type: Bug
