Repository projectdiscovery/nuclei, pull requests merged in 2022-05, with the labels that each got.

#1938 Fix for post body with debug flag #1929
  v2/pkg/protocols/http/utils.go
Labels: Status: Review Needed, Type: Bug

#1886 alternative server if a server failed
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/interactsh/interactsh.go
Labels: Status: Completed, Type: Bug

#1951 Fixing directory walk error check on windows
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/internal/runner/templates.go
  v2/pkg/catalog/find.go
  v2/pkg/protocols/common/compare/compare.go
  v2/pkg/protocols/file/find.go
  v2/pkg/protocols/offlinehttp/find.go
Labels: Status: Review Needed, Type: Bug

#1968 Use nuclei-templates instead of custom autoscan directory list
  v2/pkg/protocols/common/automaticscan/automaticscan.go
Labels: Status: Completed, Status: Review Needed

#1975 Fixed query parameter addition to http raw requests
  v2/pkg/protocols/http/raw/raw.go
Labels: Status: Completed

#1969 Added mutex to output writing
  v2/pkg/output/output.go
Labels: Status: Review Needed

#1964 Adding global SNI support for HTTP protocol via CLI
  README.md
  integration_tests/http/get-sni.yaml
  v2/cmd/integration-test/http.go
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Enhancement

#1944 sonar category: String literals should not be duplicated
  v2/pkg/core/workflow_execute.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/signer/aws.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/reporting/format/format.go
  v2/pkg/reporting/reporting.go
  v2/pkg/reporting/trackers/jira/jira.go
  v2/pkg/types/resume.go
Labels: Priority: Medium, Status: Review Needed

#1970 Adding SNI override via request annotations
  integration_tests/http/get-override-sni.yaml
  v2/cmd/integration-test/http.go
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/protocolstate/state.go
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/http/request_annotations.go
  v2/pkg/reporting/exporters/es/elasticsearch.go
Labels: Status: Review Needed, Type: Enhancement

#1930 chore(deps): Bump sarif to v2
  v2/go.mod
  v2/go.sum
  v2/pkg/reporting/exporters/sarif/sarif.go
Labels: Type: Maintenance

#1881 Appending new references to existing ones
  v2/cmd/cve-annotate/main.go
  v2/go.mod
  v2/go.sum
Labels: Status: Review Needed, Type: Maintenance

#1985 Added urldns gadget from ysoserial
  v2/pkg/protocols/common/helpers/deserialization/java.go
Labels: Status: Review Needed

#1981 Iterating payloads over HTTP path/raw sequence
  v2/pkg/protocols/http/request_generator.go
Labels: Status: Review Needed, Type: Bug

#2037 Disable printing variables in http protocol output
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed

#2051 Fixed template validation edge cases
  v2/internal/runner/runner.go
  v2/pkg/catalog/loader/loader.go
Labels: Status: Review Needed

#2064 Adding variables support for headless templates
  v2/pkg/protocols/common/generators/maps.go
  v2/pkg/protocols/common/generators/maps_test.go
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dns_test.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/build_request_test.go
Labels: Status: Review Needed, Type: Enhancement

#2077 Adding CLI SNI support to unsafe http
  integration_tests/http/get-sni-unsafe.yaml
  v2/cmd/integration-test/http.go
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/utils.go
Labels: Status: Review Needed, Type: Enhancement

#2081 Fixed websocket status-101 response reading for http
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed

#2030 Increasing buffer size on AND condition
  integration_tests/file/data/test1.txt
  integration_tests/file/data/test2.txt
  integration_tests/file/data/test3.txt
  integration_tests/file/extract.yaml
  integration_tests/file/matcher-with-and.yaml
  integration_tests/file/matcher-with-or.yaml
  v2/cmd/integration-test/file.go
  v2/cmd/integration-test/integration-test.go
  v2/pkg/protocols/file/request.go
Labels: Status: Review Needed, Type: Bug

#1949 Added hang monitor for goroutine dumping
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/types/types.go
  v2/pkg/utils/monitor/monitor.go
  v2/pkg/utils/monitor/monitor_test.go
Labels: Status: Review Needed, Type: Enhancement

#2052 Added header as DSL part value
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/http/operators_test.go
Labels: Status: Completed

#2050 Added redirected matched URL + stop-at-first-match for redirect chains
  integration_tests/http/redirect-match-url.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed
