Repository projectdiscovery/nuclei, pull requests merged in 2022-01, with the labels that each got.

#1308 Adding stop-resume support
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/internal/runner/runner.go
  v2/pkg/core/execute.go
  v2/pkg/protocols/protocols.go
  v2/pkg/templates/cluster.go
  v2/pkg/types/resume.go
  v2/pkg/types/types.go
Labels: Status: Review Needed, Type: Enhancement

#1446 Fixing 307/308 follow redirects with empty body
  v2/pkg/protocols/http/utils.go
Labels: Status: Review Needed, Type: Bug

#1444 Replacing murmur3 with internal safe-pointer version
  v2/pkg/operators/common/dsl/dsl.go
Labels: Status: Review Needed, Type: Bug

#1438 Fixing socks5 proxy for HTTP RFC standard requests
  v2/pkg/protocols/http/httpclientpool/clientpool.go
Labels: Status: Review Needed, Type: Bug

#1465 Fixing typo in request/response history
  v2/pkg/protocols/headless/engine/rules.go
Labels: Type: Bug

#1448 Adding support for template id based execution
  v2/cmd/nuclei/main.go
  v2/internal/runner/options.go
  v2/pkg/catalog/loader/filter/tag_filter.go
  v2/pkg/catalog/loader/filter/tag_filter_test.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/parsers/parser.go
  v2/pkg/parsers/workflow_loader.go
  v2/pkg/types/types.go
  v2/pkg/utils/utils.go
Labels: Status: Review Needed, Type: Enhancement

#1440 Replacing expression regex with lexical analyzer
  v2/pkg/protocols/common/expressions/expressions.go
  v2/pkg/protocols/common/expressions/expressions_test.go
  v2/pkg/protocols/common/generators/maps.go
  v2/pkg/protocols/common/marker/marker.go
  v2/pkg/protocols/common/replacer/replacer.go
  v2/pkg/protocols/headless/engine/page_actions.go
Labels: Status: Review Needed, Type: Bug

#1443 Improving payloads support in AWS self-contained requests
  v2/pkg/protocols/common/expressions/variables.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/signer/aws.go
Labels: Status: Completed, Type: Bug

#1441 Adding support for ignore file path override if custom config file is used
  v2/cmd/nuclei/main.go
  v2/pkg/catalog/config/config.go
Labels: Status: Review Needed, Type: Bug

#1445 Fixing full URL output with unsafe requests
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Bug

#1468 Added interactsh additional variables support
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/operators/operators.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/dns/operators.go
  v2/pkg/protocols/file/operators.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/network/operators.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/offlinehttp/operators.go
  v2/pkg/protocols/protocols.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#1488 Excluding non yaml file from new additions loading
  v2/internal/runner/runner.go
  v2/pkg/templates/templates.go
Labels: Status: Review Needed, Type: Bug

#1484 Adding support for Debug http verb
  v2/pkg/protocols/http/http_method_types.go
Labels: Status: Review Needed, Type: Bug

#1490 Extending http variables list with dns generated variables
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dns_test.go
  v2/pkg/protocols/http/build_request.go
Labels: Status: Review Needed, Type: Enhancement

#1492 Do not print redundant color log info with blank severity
  v2/internal/colorizer/colorizer.go
Labels: Status: Review Needed

#1500 Fixing race-requests block on curl generation command
  integration_tests/http/race-multiple.yaml
  integration_tests/http/race-simple.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Bug

#1503 DSL concat function
  integration_tests/http/dsl-functions.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
  v2/pkg/protocols/common/expressions/expressions_test.go
  v2/pkg/protocols/common/expressions/variables.go
Labels: Type: Enhancement

#1511 Adding auto-PTR IP to FQDN
  integration_tests/dns/ptr.yaml
  v2/cmd/integration-test/dns.go
  v2/pkg/protocols/dns/dns.go
Labels: Status: Review Needed, Type: Bug

#1494 Fixed stats calculation for payloads in http base request
  v2/internal/runner/runner.go
  v2/pkg/protocols/http/http.go
Labels: Status: Review Needed, Type: Bug

#1506 fix: strip default http/https ports from Host header
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/request_generator.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#1537 Headless limited code refactor for better readability
  v2/pkg/protocols/headless/engine/rules.go
Labels: Type: Maintenance

#1516 Implementing lexer with runtime expression validation
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/expressions/expressions.go
  v2/pkg/protocols/common/expressions/expressions_test.go
Labels: Status: Completed, Type: Enhancement

#1491 Added debug-req/resp support for interactsh interactions
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/interactsh/interactsh.go
Labels: Status: Completed

#1472 Add support to run remote template
  v2/cmd/integration-test/loader.go
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/pkg/catalog/find.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/catalog/loader/loader_test.go
  v2/pkg/catalog/loader/remote_loader.go
  v2/pkg/parsers/parser.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/templates/compile.go
  v2/pkg/types/types.go
  v2/pkg/utils/utils.go
Labels: Status: Completed, Type: Enhancement
