Repository projectdiscovery/nuclei, pull requests merged in 2022-12, with the labels that each got.

#2825 Issue 2772 s3 provider support
  .github/workflows/build-test.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish-docs.yaml
  .github/workflows/template-validate.yml
  README.md
  v2/Makefile
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/internal/runner/update.go
  v2/pkg/catalog/config/config.go
  v2/pkg/external/customtemplates/github.go
  v2/pkg/external/customtemplates/github_test.go
  v2/pkg/external/customtemplates/s3.go
  v2/pkg/external/customtemplates/templates_provider.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2950 Fixing reported dialed ip
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/ssl/ssl.go
Labels: Type: Bug

#2782 Adding client/server hello in ssl templates
  v2/pkg/protocols/ssl/ssl.go
Labels: Status: In Progress, Type: Enhancement

#2962 Added timestamp optional flag + user-agent to probing
  README.md
  v2/cmd/nuclei/main.go
  v2/internal/runner/inputs.go
  v2/internal/runner/runner.go
  v2/pkg/output/format_screen.go
  v2/pkg/output/output.go
  v2/pkg/protocols/http/fuzz/parts.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#2919 added force http2 option
  README.md
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#3011 Adding custom ip to protocol generated variables
  v2/internal/runner/templates.go
  v2/pkg/protocols/common/contextargs/variables.go
  v2/pkg/protocols/common/updatecheck/client.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/http/utils/variables.go
  v2/pkg/protocols/http/utils/variables_test.go
Labels: Type: Bug

#3019 Added http probing to clustering + add disable-clustering flag
  v2/cmd/integration-test/http.go
  v2/cmd/nuclei/main.go
  v2/pkg/templates/cluster.go
  v2/pkg/types/types.go
Labels: Status: Review Needed

#3010 automerge url parameters from input and templates
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/raw/raw_test.go
  v2/pkg/protocols/http/utils/url.go
  v2/pkg/protocols/http/utils/url_test.go
Labels: Type: Enhancement, Type: Bug

#1767 Extending YAML to support include preprocessing
  v2/pkg/parsers/parser.go
  v2/pkg/utils/utils.go
  v2/pkg/utils/yaml/preprocess.go
Labels: Status: Review Needed, Type: Enhancement

#3014 Replace break line characters with HTML notation when exporting to markdown
  v2/pkg/reporting/format/format.go
Labels: Type: Bug

#2890 Resuming rewriting the output file contents, so previous data removed
  v2/internal/runner/runner.go
  v2/pkg/output/file_output_writer.go
  v2/pkg/output/output.go
  v2/pkg/output/output_test.go
Labels: Type: Bug

#3034 add stop-at-first-match for headless protocol
  .github/workflows/publish-docs.yaml
  v2/pkg/protocols/headless/headless.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/protocols.go
Labels: Type: Bug

#3052 Fix memory leak on hmap with LRU
  v2/go.mod
  v2/go.sum
  v2/pkg/core/inputs/hybrid/hmap.go
Labels: Type: Bug

#3030 The debug flags do not work correctly with headless templates
  v2/pkg/protocols/headless/request.go
Labels: Type: Bug

#3069 CLI variables are not accessible in SSL Protocol
  integration_tests/ssl/ssl-with-vars.yaml
  v2/cmd/integration-test/ssl.go
  v2/pkg/protocols/ssl/ssl.go
Labels: Type: Bug

#3037 Issue 3033 deny list
  v2/pkg/input/input.go
  v2/pkg/operators/operators.go
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/protocols/common/generators/maps.go
  v2/pkg/protocols/common/generators/validate.go
  v2/pkg/protocols/file/file.go
  v2/pkg/protocols/file/find_test.go
  v2/pkg/protocols/file/operators_test.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/network/request.go
Labels: Type: Bug

#3073 Removing most go routine leaks
  v2/cmd/integration-test/code.go
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/common/uncover/uncover.go
Labels: Type: Bug

#3075 adds scan strategy
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/core/execute.go
  v2/pkg/types/types.go
Labels: Status: Revision Needed, Type: Enhancement

#3089 Initialize flags with nil slice
  v2/cmd/nuclei/main.go
Labels: Type: Maintenance

#3054 Add support to query DNS TLSA record
  integration_tests/dns/tlsa.yaml
  v2/cmd/integration-test/dns.go
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dns_types.go
Labels: Type: Enhancement

#2995 Removing unwanted print debug
  v2/pkg/operators/common/dsl/dsl.go
Labels: Type: Bug

#3100 Adding empty comparison for scan strategy
  SYNTAX-REFERENCE.md
  nuclei-jsonschema.json
  v2/pkg/core/execute.go
  v2/pkg/templates/templates_doc.go
Labels: Type: Bug

#3107 Replacing unstable interactsh with scanme.sh
  integration_tests/http/dsl-functions.yaml
Labels: Type: Maintenance
