Repository projectdiscovery/nuclei, pull requests merged in 2023-03, with the labels that each got.

#3381 Using retryablehttp for api request
  v2/cmd/cve-annotate/main.go
  v2/cmd/integration-test/http.go
  v2/cmd/tools/fuzzplayground/main.go
  v2/internal/runner/runner.go
  v2/internal/runner/update.go
  v2/pkg/catalog/loader/remote_loader.go
  v2/pkg/protocols/common/updatecheck/client.go
  v2/pkg/utils/utils.go
Labels: Type: Maintenance

#3321 resolve() helper function
  integration_tests/http/dsl-functions.yaml
  v2/go.mod
  v2/go.sum
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
Labels: Type: Enhancement

#3373 Adding one-time method override
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/engine/rules.go
Labels: Type: Bug

#3376 Fixing atomic bool check
  v2/pkg/core/execute_options.go
  v2/pkg/core/executors.go
Labels: Type: Bug

#3400 Change "Operative System" to "Operating System"
  v2/internal/runner/healthcheck.go
Labels: Type: Enhancement

#3424 json templates support (load with flags, run & validate )
  v2/cmd/sign-templates/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/cloud.go
  v2/internal/runner/runner.go
  v2/pkg/catalog/config/template.go
  v2/pkg/catalog/disk/find.go
  v2/pkg/catalog/disk/known-files.go
  v2/pkg/catalog/loader/remote_loader.go
  v2/pkg/parsers/parser.go
  v2/pkg/templates/extensions/extensions.go
  v2/pkg/templates/templates.go
  v2/pkg/utils/utils.go
  v2/pkg/utils/yaml/preprocess.go
Labels: Type: Enhancement
