Repository projectdiscovery/nuclei, pull requests merged in 2023-07, with the labels that each got.

#3887 preserve order of query parameters
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/fuzz/execute.go
  v2/pkg/protocols/common/fuzz/parts.go
  v2/pkg/protocols/common/fuzz/parts_test.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/raw/raw_test.go
  v2/pkg/protocols/utils/variables.go
Labels: Type: Bug, Type: Maintenance

#3888 support disable-path-automerge in unsafe mode
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/request.go
Labels: Status: Review Needed, Type: Bug

#3710 Exclude Raw Request Payloads
  README.md
  README_CN.md
  README_ID.md
  README_KR.md
  v2/cmd/nuclei/main.go
  v2/internal/runner/runner.go
  v2/pkg/output/output.go
  v2/pkg/reporting/exporters/jsonexporter/jsonexporter.go
  v2/pkg/reporting/exporters/jsonl/jsonl.go
  v2/pkg/reporting/exporters/markdown/markdown.go
  v2/pkg/testutils/testutils.go
  v2/pkg/types/types.go
Labels: Type: Maintenance

#3903 Bugfix 3871 workflow concurrency
  v2/cmd/nuclei/test.yaml
  v2/pkg/core/workflow_execute.go
  v2/pkg/templates/compile.go
Labels: Type: Bug

#3857 Automate merging of dependabot PRs to dep branch
  .github/dependabot.yml
  .github/workflows/auto-merge.yml
  .github/workflows/sync-dep.yml
Labels: Type: Maintenance

#3906 Adding jarm helper via dsl
  integration_tests/http/dsl-functions.yaml
  v2/cmd/integration-test/http.go
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/expressions/variables.go
Labels: Type: Enhancement

#3962 Remove Unused Update File
  v2/pkg/protocols/common/updatecheck/client.go
Labels: Type: Maintenance

#3961 Markdown Export Sorting
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/reporting/exporters/markdown/markdown.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#3955 Adding httpx probe to simple input handing
  v2/examples/simple.go
  v2/internal/runner/inputs.go
  v2/pkg/core/inputs/inputs.go
  v2/pkg/utils/http_probe.go
Labels: Type: Bug

#3995 Fixing certificate expiration date
  integration_tests/generic/auth/certificate/assets/client.crt
  integration_tests/generic/auth/certificate/assets/client.key
  integration_tests/generic/auth/certificate/assets/server.crt
  v2/cmd/integration-test/generic.go
Labels: Type: Bug

#3958 headless: automerge and other improvements
  v2/pkg/protocols/headless/engine/instance.go
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/utils/http/requtils.go
  v2/pkg/protocols/utils/http/requtils_test.go
Labels: Status: Review Needed

#3977 Omit Empty Fields
  v2/pkg/model/model.go
  v2/pkg/model/model_test.go
  v2/pkg/model/types/stringslice/stringslice_raw.go
  v2/pkg/output/output.go
  v2/pkg/reporting/format/format_utils_test.go
  v2/pkg/templates/templates_doc_examples.go
Labels: Type: Maintenance

#3951 add headless options flag
  README.md
  v2/cmd/integration-test/code.go
  v2/cmd/integration-test/custom-dir.go
  v2/cmd/integration-test/dns.go
  v2/cmd/integration-test/file.go
  v2/cmd/integration-test/fuzz.go
  v2/cmd/integration-test/generic.go
  v2/cmd/integration-test/headless.go
  v2/cmd/integration-test/http.go
  v2/cmd/integration-test/integration-test.go
  v2/cmd/integration-test/interactsh.go
  v2/cmd/integration-test/loader.go
  v2/cmd/integration-test/network.go
  v2/cmd/integration-test/offline-http.go
  v2/cmd/integration-test/ssl.go
  v2/cmd/integration-test/template-dir.go
  v2/cmd/integration-test/template-path.go
  v2/cmd/integration-test/websocket.go
  v2/cmd/integration-test/whois.go
  v2/cmd/integration-test/workflow.go
  v2/cmd/nuclei/main.go
  v2/internal/runner/options.go
  v2/internal/runner/options_test.go
  v2/pkg/protocols/headless/engine/engine.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#4003 Fixing dsl integration tests syntax
  v2/cmd/integration-test/dsl.go
Labels: Type: Maintenance
