Repository projectdiscovery/nuclei, pull requests merged in 2023-04, with the labels that each got.

#3523 Replacing ccache with generic gcache
  .github/workflows/build-test.yml
  integration_tests/http/interactsh-stop-at-first-match.yaml
  v2/cmd/integration-test/code.go
  v2/cmd/integration-test/http.go
  v2/cmd/integration-test/integration-test.go
  v2/cmd/integration-test/interactsh.go
  v2/examples/simple.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/output/output.go
  v2/pkg/protocols/common/interactsh/const.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/common/interactsh/options.go
  v2/pkg/protocols/http/build_request_test.go
  v2/pkg/protocols/http/request.go
  v2/pkg/utils/atomcache/atomcache.go
Labels: Type: Enhancement

#3571 Replacing goos with osutils
  v2/cmd/nuclei/main.go
  v2/pkg/protocols/common/generators/load_test.go
  v2/pkg/protocols/headless/engine/engine.go
Labels: Type: Maintenance

#3590 Additional nil check on interactsh client
  v2/pkg/protocols/common/interactsh/const.go
  v2/pkg/protocols/common/interactsh/interactsh.go
Labels: Type: Bug

#3606 Update -tc flag to filter fields within the classification section
  v2/pkg/catalog/loader/filter/tag_filter.go
  v2/pkg/catalog/loader/filter/tag_filter_test.go
Labels: Status: Review Needed

#3540 Check severity att while validating
  v2/pkg/catalog/loader/loader.go
  v2/pkg/parsers/parser.go
  v2/pkg/parsers/parser_test.go
  v2/pkg/parsers/workflow_loader.go
Labels: Status: Revision Needed
