Repository projectdiscovery/nuclei, pull requests merged in 2023-06, with the labels that each got.

#3546 Extending multistep support
  v2/pkg/protocols/common/expressions/expressions.go
  v2/pkg/protocols/common/expressions/expressions_test.go
  v2/pkg/protocols/network/request.go
Labels: Type: Enhancement

#3672 support for dynamic variables in template context (multi protocol execution)
  SYNTAX-REFERENCE.md
  integration_tests/fuzz/fuzz-headless.yaml
  integration_tests/headless/headless-header-status-test.yaml
  integration_tests/multi/dynamic-values.yaml
  integration_tests/multi/evaluate-variables.yaml
  integration_tests/multi/exported-response-vars.yaml
  nuclei-jsonschema.json
  v2/cmd/integration-test/fuzz.go
  v2/cmd/integration-test/headless.go
  v2/cmd/integration-test/integration-test.go
  v2/cmd/integration-test/multi.go
  v2/pkg/operators/matchers/compile.go
  v2/pkg/protocols/common/contextargs/args.go
  v2/pkg/protocols/common/contextargs/contextargs.go
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/protocols/common/fuzz/doc.go
  v2/pkg/protocols/common/fuzz/execute.go
  v2/pkg/protocols/common/fuzz/execute_test.go
  v2/pkg/protocols/common/fuzz/fuzz.go
  v2/pkg/protocols/common/fuzz/fuzz_test.go
  v2/pkg/protocols/common/fuzz/parts.go
  v2/pkg/protocols/common/fuzz/parts_test.go
  v2/pkg/protocols/common/utils/vardump/dump.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/file/request.go
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/headless.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/http.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/multi/README.md
  v2/pkg/protocols/multi/doc.go
  v2/pkg/protocols/multi/request.go
  v2/pkg/protocols/multi/request_test.go
  v2/pkg/protocols/multi/testcases/multiprotodynamic.yaml
  v2/pkg/protocols/multi/testcases/multiprotowithprefix.yaml
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/offlinehttp/request.go
  v2/pkg/protocols/protocols.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/protocols/whois/whois.go
  v2/pkg/templates/compile.go
  v2/pkg/templates/compile_test.go
  v2/pkg/templates/templates.go
  v2/pkg/templates/templates_doc.go
  v2/pkg/templates/tests/multiproto.json
  v2/pkg/templates/tests/multiproto.yaml
  v2/pkg/templates/types/types.go
  v2/pkg/testutils/testutils.go
Labels: Status: Review Needed

#3831 fix output path in unsafe mode
  v2/pkg/protocols/http/request.go
Labels: Type: Bug, regression

#3844 Adding random tls impersonate
  README.md
  v2/cmd/functional-test/testcases.txt
  v2/cmd/nuclei/main.go
  v2/cmd/nuclei/test.yaml
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/types/types.go
Labels: Type: Enhancement

#3859 Better dbg message formatting
  v2/pkg/core/executors.go
Labels: Type: Maintenance

#3853 Refactoring variables logic with map + get public ip
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/variables/variables.go
  v2/pkg/protocols/utils/variables.go
Labels: Type: Enhancement

#3849 fix(reporting): Markdown and Jira exporter fixes
  v2/pkg/reporting/exporters/markdown/markdown.go
  v2/pkg/reporting/exporters/markdown/util/markdown_formatter.go
  v2/pkg/reporting/exporters/markdown/util/markdown_utils.go
  v2/pkg/reporting/exporters/markdown/util/markdown_utils_test.go
  v2/pkg/reporting/exporters/sarif/sarif.go
  v2/pkg/reporting/format/format.go
  v2/pkg/reporting/format/format_utils.go
  v2/pkg/reporting/format/format_utils_test.go
  v2/pkg/reporting/trackers/github/github.go
  v2/pkg/reporting/trackers/gitlab/gitlab.go
  v2/pkg/reporting/trackers/jira/jira.go
  v2/pkg/reporting/trackers/jira/jira_test.go
Labels: Type: Bug

#3850 Extend headless contextargs
  .github/workflows/build-test.yml
  .github/workflows/functional-test.yml
  integration_tests/workflow/headless-1.yaml
  integration_tests/workflow/http-1.yaml
  integration_tests/workflow/http-2.yaml
  integration_tests/workflow/http-3.yaml
  integration_tests/workflow/http-value-share-template-1.yaml
  integration_tests/workflow/http-value-share-template-2.yaml
  integration_tests/workflow/match-1.yaml
  integration_tests/workflow/match-2.yaml
  integration_tests/workflow/nomatch-1.yaml
  integration_tests/workflow/shared-cookie.yaml
  v2/cmd/integration-test/workflow.go
  v2/pkg/protocols/common/fuzz/execute.go
  v2/pkg/protocols/common/fuzz/execute_test.go
  v2/pkg/protocols/common/fuzz/parts.go
  v2/pkg/protocols/common/fuzz/parts_test.go
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/engine/page_actions_test.go
  v2/pkg/protocols/headless/engine/rules.go
  v2/pkg/protocols/headless/headless.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/offlinehttp/request.go
  v2/pkg/protocols/utils/utils.go
Labels: Status: Review Needed, Type: Enhancement

#3845 set read and write deadline
  v2/pkg/protocols/network/request.go
Labels: Status: Review Needed, Type: Bug

#3770 fix showing multiple failure matches per template on -ms set
  integration_tests/http/matcher-status.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/output/output.go
  v2/pkg/protocols/common/executer/executer.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/network/request_test.go
  v2/pkg/testutils/integration.go
Labels: Status: Revision Needed, Type: Bug
