Repository projectdiscovery/nuclei, pull requests merged in 2023-01, with the labels that each got.

#3047 #3046 persistent failed item status and #2065 failed items reporting error once
  .github/workflows/build-test.yml
  .github/workflows/changelog-indexer.yaml
  .github/workflows/functional-test.yml
  .github/workflows/lint-test.yml
  .github/workflows/publish-docs.yaml
  .github/workflows/release-binary.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/template-validate.yml
  README.md
  README_CN.md
  README_ID.md
  README_KR.md
  helm/templates/interactsh-ingress.yaml
  v2/go.mod
  v2/pkg/protocols/common/hosterrorscache/hosterrorscache.go
  v2/pkg/protocols/common/hosterrorscache/hosterrorscache_test.go
Labels: Type: Bug

#3134 Removing unused code in integration tests
  v2/cmd/integration-test/dns.go
  v2/cmd/integration-test/http.go
  v2/cmd/integration-test/network.go
  v2/cmd/integration-test/template-dir.go
Labels: Type: Maintenance

#3150 urlencode key characters only
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/fuzz/parts.go
  v2/pkg/protocols/http/fuzz/parts_test.go
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/websocket/websocket.go
Labels: Type: Enhancement, Type: Bug

#3091 extending request/response hijacking with native calls
  integration_tests/headless/file-upload.yaml
  v2/cmd/integration-test/headless.go
  v2/pkg/protocols/headless/engine/hijack.go
  v2/pkg/protocols/headless/engine/page.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/headless/engine/page_actions_test.go
  v2/pkg/protocols/headless/engine/rules.go
  v2/pkg/protocols/headless/request.go
Labels: Type: Bug

#3146 Extending advanced filtering
  v2/cmd/functional-test/testcases.txt
  v2/pkg/catalog/loader/filter/tag_filter.go
Labels: Type: Enhancement

#3147 Adding content length edge cases
  integration_tests/http/cl-body-with-header.yaml
  integration_tests/http/cl-body-without-header.yaml
  v2/cmd/integration-test/http.go
Labels: Type: Maintenance

#3110 Add timestamp for debug logs
  v2/cmd/nuclei/main.go
  v2/go.mod
  v2/go.sum
Labels: Type: Enhancement

#3187 Moving examples to go file
  .github/workflows/build-test.yml
  README.md
  v2/examples/simple.go
Labels: Type: Maintenance

#3111 lowering hmap storage requirement via omitempty
  v2/pkg/protocols/common/contextargs/metainput.go
Labels: Type: Bug

#3129 Markdown Reporting Index File
  v2/pkg/reporting/exporters/markdown/markdown.go
Labels: Type: Enhancement

#3205 Fixed panic with non-existent target and no cloud flag typo
  v2/internal/runner/runner.go
Labels: Status: Review Needed

#3204 Added clustering support for DNS protocol templates
  v2/internal/runner/runner.go
  v2/pkg/protocols/dns/cluster.go
  v2/pkg/protocols/dns/dns.go
  v2/pkg/templates/cluster.go
  v2/pkg/templates/cluster_test.go
Labels: Status: Review Needed

#3209 Added clustering support for TLS templates
  v2/pkg/protocols/dns/cluster.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/templates/cluster.go
  v2/pkg/templates/cluster_test.go
Labels: Status: Review Needed

#3219 Adding support for nmhe
  README.md
  README_CN.md
  README_ID.md
  README_KR.md
  v2/cmd/nuclei/main.go
  v2/internal/runner/options.go
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/hosterrorscache/hosterrorscache.go
  v2/pkg/types/types.go
Labels: Type: Enhancement
