Repository projectdiscovery/nuclei, pull requests merged in 2023-08, with the labels that each got.

#4039 use default perms
  .gitignore
  v2/cmd/integration-test/generic.go
  v2/cmd/integration-test/loader.go
  v2/go.mod
  v2/go.sum
  v2/internal/runner/runner.go
  v2/pkg/protocols/file/find_test.go
  v2/pkg/protocols/file/request_test.go
  v2/pkg/protocols/offlinehttp/find_test.go
  v2/pkg/utils/monitor/monitor.go
Labels: Type: Maintenance

#4043 tlsx / dsl dep update
  v2/go.mod
  v2/go.sum
Labels: Type: Maintenance

#4050 Adding default resp size to options
  v2/pkg/types/types.go
Labels: Type: Bug

#4087 XPath matcher support
  docs/template-guide/operators/matchers.mdx
  v2/pkg/operators/matchers/match.go
  v2/pkg/operators/matchers/match_test.go
  v2/pkg/operators/matchers/matchers.go
  v2/pkg/operators/matchers/matchers_types.go
  v2/pkg/operators/matchers/validate.go
  v2/pkg/operators/matchers/validate_test.go
  v2/pkg/protocols/dns/operators.go
  v2/pkg/protocols/file/operators.go
  v2/pkg/protocols/headless/operators.go
  v2/pkg/protocols/http/operators.go
  v2/pkg/protocols/network/operators.go
  v2/pkg/protocols/offlinehttp/operators.go
  v2/pkg/protocols/protocols.go
Labels: Type: Enhancement

#4097 use stringsutil.HasPrefixAnyI
  v2/pkg/protocols/common/protocolstate/headless.go
Labels: Type: Maintenance

#4099 Update mock-outputwriter to write the failed event
  v2/pkg/testutils/testutils.go
Labels: Type: Enhancement
