Repository projectdiscovery/nuclei, pull requests merged in 2023-05, with the labels that each got.

#3601 aws signer: fix missing x-content-sha256 header
  integration_tests/http/raw-unsafe-with-params.yaml
  integration_tests/http/raw-with-params.yaml
  integration_tests/http/self-contained-with-path.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/protocols/common/variables/doc.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/raw/raw.go
  v2/pkg/protocols/http/signature.go
  v2/pkg/protocols/http/signer/aws-sign.go
Labels: Status: Review Needed

#3599 Issue 3564 var override
  integration_tests/http/variable-dsl-function.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/protocols/common/variables/variables.go
  v2/pkg/protocols/dns/dns.go
  v2/pkg/protocols/dns/dns_test.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/utils/variables.go
  v2/pkg/protocols/http/utils/variables_test.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/utils/variables.go
  v2/pkg/protocols/utils/variables_test.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/protocols/whois/whois.go
Labels: Status: Review Needed

#3607 Add utility to write max-requests to templates
  v2/cmd/cve-annotate/main.go
Labels: Status: Review Needed

#3680 Adding interact keepalive to reduce server-side id pruning
  .github/workflows/build-test.yml
  .github/workflows/functional-test.yml
  .github/workflows/lint-test.yml
  .github/workflows/publish-docs.yaml
  .github/workflows/release-binary.yml
  .github/workflows/template-validate.yml
  README.md
  README_CN.md
  README_ID.md
  README_KR.md
  helm/templates/interactsh-ingress.yaml
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/common/randomip/randomip.go
Labels: Type: Bug

#3692 Adding support for constants
  integration_tests/http/cli-with-constants.yaml
  v2/cmd/integration-test/http.go
  v2/pkg/protocols/common/variables/doc.go
  v2/pkg/protocols/dns/request.go
  v2/pkg/protocols/headless/engine/http_client.go
  v2/pkg/protocols/headless/request.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/fuzz/execute.go
  v2/pkg/protocols/http/request.go
  v2/pkg/protocols/network/request.go
  v2/pkg/protocols/protocols.go
  v2/pkg/protocols/ssl/ssl.go
  v2/pkg/protocols/websocket/websocket.go
  v2/pkg/protocols/whois/whois.go
  v2/pkg/templates/compile.go
  v2/pkg/templates/templates.go
Labels: Type: Enhancement

#3745 removing .yml from remote loading
  v2/pkg/catalog/loader/remote_loader.go
Labels: Type: Bug
