Repository projectdiscovery/nuclei, pull requests merged in 2023-02, with the labels that each got.

#3261 Use httpx as library for http probing
  v2/go.mod
  v2/go.sum
  v2/internal/runner/inputs.go
Labels: Status: Review Needed

#3098 Improve passive templates error handling
  v2/internal/runner/runner.go
  v2/pkg/catalog/loader/loader.go
  v2/pkg/templates/compile.go
Labels: Type: Bug, Type: Maintenance

#3240 adding json schema for extractor
  v2/cmd/docgen/docgen.go
  v2/pkg/operators/extractors/extractors.go
Labels: Type: Bug

#3276 Adding interactsh support to sni
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/common/variables/variables.go
  v2/pkg/protocols/headless/engine/page_actions.go
  v2/pkg/protocols/http/build_request.go
  v2/pkg/protocols/http/fuzz/parts.go
  v2/pkg/protocols/http/request_annotations.go
  v2/pkg/protocols/http/request_annotations_test.go
  v2/pkg/protocols/network/request.go
Labels: Type: Enhancement

#3296 fix publish docs
  .github/workflows/publish-docs.yaml
  SYNTAX-REFERENCE.md
  nuclei-jsonschema.json
  v2/pkg/templates/templates_doc.go
Labels: github_actions

#3291 Using retryablehttp for templates loading
  v2/pkg/templates/compile.go
  v2/pkg/templates/compile_test.go
Labels: Type: Bug

#3312 clear after stop
  v2/cmd/integration-test/http.go
  v2/go.mod
  v2/go.sum
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/http/httpclientpool/clientpool.go
  v2/pkg/protocols/http/request.go
  v2/pkg/utils/atomcache/atomcache.go
Labels: Type: Bug

#3322 Added optional doNotCache to protocols.ExecuterOptions
  v2/pkg/protocols/protocols.go
  v2/pkg/templates/compile.go
Labels: Status: Review Needed

#3280 Converting reporting client to interface
  v2/internal/runner/runner.go
  v2/pkg/protocols/common/helpers/writer/writer.go
  v2/pkg/protocols/common/interactsh/interactsh.go
  v2/pkg/protocols/protocols.go
  v2/pkg/reporting/client.go
  v2/pkg/reporting/dedupe/dedupe.go
  v2/pkg/reporting/options.go
  v2/pkg/reporting/reporting.go
Labels: Type: Enhancement

#3029 Add template sign/verify functionality
  v2/cmd/sign-templates/main.go
  v2/go.mod
  v2/pkg/operators/common/dsl/dsl.go
  v2/pkg/operators/common/dsl/dsl_test.go
  v2/pkg/parsers/parser.go
  v2/pkg/templates/signer/default.go
  v2/pkg/templates/signer/ecdsa_public_key.go
  v2/pkg/templates/signer/ecdsa_public_key.pem
  v2/pkg/templates/signer/options.go
  v2/pkg/templates/signer/signer.go
  v2/pkg/templates/signer/util.go
  v2/pkg/templates/templates.go
Labels: Type: Enhancement

#3368 Mapcidr defaultclient
  v2/go.mod
  v2/go.sum
  v2/pkg/core/inputs/hybrid/hmap.go
Labels: Type: Maintenance
