Repository projectdiscovery/nuclei, pull requests merged in 2024-04, with the labels that each got.

#4992 feat: fixed bug due to parallel auto setting in http
  pkg/protocols/http/http.go
Labels: Status: Review Needed

#4986 Initial Refactor for speed control
  .github/workflows/build-test.yml
  cmd/nuclei/main.go
  examples/advanced/advanced.go
  examples/with_speed_control/main.go
  go.mod
  go.sum
  internal/runner/inputs.go
  internal/runner/runner.go
  lib/config.go
  lib/multi.go
  lib/sdk.go
  lib/sdk_private.go
  pkg/core/engine.go
  pkg/core/execute_options.go
  pkg/core/executors.go
  pkg/core/workflow_execute.go
  pkg/core/workpool.go
  pkg/js/compiler/non-pool.go
  pkg/js/compiler/pool.go
  pkg/protocols/common/automaticscan/automaticscan.go
  pkg/protocols/dns/request.go
  pkg/protocols/file/request.go
  pkg/protocols/headless/engine/page_actions.go
  pkg/protocols/http/httputils/spm.go
  pkg/protocols/http/request.go
  pkg/protocols/http/request_fuzz.go
  pkg/protocols/javascript/js.go
  pkg/protocols/network/networkclientpool/clientpool.go
  pkg/protocols/network/request.go
  pkg/protocols/offlinehttp/request.go
  pkg/protocols/protocols.go
  pkg/testutils/testutils.go
  pkg/tmplexec/flow/vm.go
  pkg/types/types.go
Labels: Type: Enhancement

#5036 Adding networkpolicy to httpx probes
  internal/runner/inputs.go
Labels: Type: Bug

#5035 Fixing internal resolver override
  pkg/protocols/common/protocolstate/state.go
  pkg/protocols/dns/dnsclientpool/clientpool.go
  pkg/types/types.go
Labels: Type: Bug

#5030 Exposing embedded api for settings control in CLI modality
  cmd/nuclei/main.go
  internal/httpapi/apiendpoint.go
  internal/runner/inputs.go
  internal/runner/runner.go
  pkg/testutils/testutils.go
  pkg/types/types.go
Labels: Type: Enhancement
